#ifndef FUN4CAL_FUN4CALHISTOBINDEFS_H
#define FUN4CAL_FUN4CALHISTOBINDEFS_H

namespace Fun4CalHistoBinDefs
{
  enum
  {
    FIRSTRUNBIN = 1,
    LASTRUNBIN,
    BORTIMEBIN,
    EORTIMEBIN,
    LASTBINPLUSONE
  };
};

#endif /* FUN4CAL_FUN4CALHISTOBINDEFS_H */
