/********************************************************************
* PHG4HoughTransform_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PHG4HoughTransform_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePHG4HoughTransform_Dict();
extern void G__cpp_setup_inheritancePHG4HoughTransform_Dict();
extern void G__cpp_setup_typetablePHG4HoughTransform_Dict();
extern void G__cpp_setup_memvarPHG4HoughTransform_Dict();
extern void G__cpp_setup_globalPHG4HoughTransform_Dict();
extern void G__cpp_setup_memfuncPHG4HoughTransform_Dict();
extern void G__cpp_setup_funcPHG4HoughTransform_Dict();
extern void G__set_cpp_environmentPHG4HoughTransform_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PHG4HoughTransform.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PHG4HoughTransform_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__PHG4HoughTransform_DictLN_string;
extern G__linked_taginfo G__PHG4HoughTransform_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PHG4HoughTransform_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHG4HoughTransform_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PHG4HoughTransform_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHG4HoughTransform_DictLN_Fun4AllBase;
extern G__linked_taginfo G__PHG4HoughTransform_DictLN_PHCompositeNode;
extern G__linked_taginfo G__PHG4HoughTransform_DictLN_SubsysReco;
extern G__linked_taginfo G__PHG4HoughTransform_DictLN_SvtxTrack;
extern G__linked_taginfo G__PHG4HoughTransform_DictLN_SvtxTrackState;
extern G__linked_taginfo G__PHG4HoughTransform_DictLN_PHG4HoughTransform;

/* STUB derived class for protected member access */
