//
// File generated by rootcint at Tue Mar 28 22:41:50 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME PHG4SvtxTrackProjection_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "PHG4SvtxTrackProjection_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void PHG4SvtxTrackProjection_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void PHG4SvtxTrackProjection_Dictionary();
   static void *new_PHG4SvtxTrackProjection(void *p = 0);
   static void *newArray_PHG4SvtxTrackProjection(Long_t size, void *p);
   static void delete_PHG4SvtxTrackProjection(void *p);
   static void deleteArray_PHG4SvtxTrackProjection(void *p);
   static void destruct_PHG4SvtxTrackProjection(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::PHG4SvtxTrackProjection*)
   {
      ::PHG4SvtxTrackProjection *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::PHG4SvtxTrackProjection),0);
      static ::ROOT::TGenericClassInfo 
         instance("PHG4SvtxTrackProjection", "./PHG4SvtxTrackProjection.h", 29,
                  typeid(::PHG4SvtxTrackProjection), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &PHG4SvtxTrackProjection_Dictionary, isa_proxy, 3,
                  sizeof(::PHG4SvtxTrackProjection) );
      instance.SetNew(&new_PHG4SvtxTrackProjection);
      instance.SetNewArray(&newArray_PHG4SvtxTrackProjection);
      instance.SetDelete(&delete_PHG4SvtxTrackProjection);
      instance.SetDeleteArray(&deleteArray_PHG4SvtxTrackProjection);
      instance.SetDestructor(&destruct_PHG4SvtxTrackProjection);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::PHG4SvtxTrackProjection*)
   {
      return GenerateInitInstanceLocal((::PHG4SvtxTrackProjection*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PHG4SvtxTrackProjection*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void PHG4SvtxTrackProjection_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::PHG4SvtxTrackProjection*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_PHG4SvtxTrackProjection(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PHG4SvtxTrackProjection : new ::PHG4SvtxTrackProjection;
   }
   static void *newArray_PHG4SvtxTrackProjection(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PHG4SvtxTrackProjection[nElements] : new ::PHG4SvtxTrackProjection[nElements];
   }
   // Wrapper around operator delete
   static void delete_PHG4SvtxTrackProjection(void *p) {
      delete ((::PHG4SvtxTrackProjection*)p);
   }
   static void deleteArray_PHG4SvtxTrackProjection(void *p) {
      delete [] ((::PHG4SvtxTrackProjection*)p);
   }
   static void destruct_PHG4SvtxTrackProjection(void *p) {
      typedef ::PHG4SvtxTrackProjection current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::PHG4SvtxTrackProjection

/********************************************************
* PHG4SvtxTrackProjection_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablePHG4SvtxTrackProjection_Dict();

extern "C" void G__set_cpp_environmentPHG4SvtxTrackProjection_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("PHG4SvtxTrackProjection.h");
  G__cpp_reset_tagtablePHG4SvtxTrackProjection_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevPHG4SvtxTrackProjection_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PHG4SvtxTrackProjection */
static int G__PHG4SvtxTrackProjection_Dict_501_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PHG4SvtxTrackProjection* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PHG4SvtxTrackProjection(*(string*) libp->para[0].ref);
     } else {
       p = new((void*) gvp) PHG4SvtxTrackProjection(*(string*) libp->para[0].ref);
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new PHG4SvtxTrackProjection[n];
       } else {
         p = new((void*) gvp) PHG4SvtxTrackProjection[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new PHG4SvtxTrackProjection;
       } else {
         p = new((void*) gvp) PHG4SvtxTrackProjection;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_PHG4SvtxTrackProjection));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4SvtxTrackProjection_Dict_501_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const PHG4SvtxTrackProjection*) G__getstructoffset())->get_mag_field());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4SvtxTrackProjection_Dict_501_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4SvtxTrackProjection*) G__getstructoffset())->set_mag_field((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__PHG4SvtxTrackProjection_Dict_501_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   PHG4SvtxTrackProjection* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new PHG4SvtxTrackProjection(*(PHG4SvtxTrackProjection*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_PHG4SvtxTrackProjection));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PHG4SvtxTrackProjection G__TPHG4SvtxTrackProjection;
static int G__PHG4SvtxTrackProjection_Dict_501_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PHG4SvtxTrackProjection*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PHG4SvtxTrackProjection*) (soff+(sizeof(PHG4SvtxTrackProjection)*i)))->~G__TPHG4SvtxTrackProjection();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PHG4SvtxTrackProjection*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PHG4SvtxTrackProjection*) (soff))->~G__TPHG4SvtxTrackProjection();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__PHG4SvtxTrackProjection_Dict_501_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PHG4SvtxTrackProjection* dest = (PHG4SvtxTrackProjection*) G__getstructoffset();
   *dest = *(PHG4SvtxTrackProjection*) libp->para[0].ref;
   const PHG4SvtxTrackProjection& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PHG4SvtxTrackProjection */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncPHG4SvtxTrackProjection_Dict {
 public:
  G__Sizep2memfuncPHG4SvtxTrackProjection_Dict(): p(&G__Sizep2memfuncPHG4SvtxTrackProjection_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncPHG4SvtxTrackProjection_Dict::*p)();
};

size_t G__get_sizep2memfuncPHG4SvtxTrackProjection_Dict()
{
  G__Sizep2memfuncPHG4SvtxTrackProjection_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancePHG4SvtxTrackProjection_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_PHG4SvtxTrackProjection))) {
     PHG4SvtxTrackProjection *G__Lderived;
     G__Lderived=(PHG4SvtxTrackProjection*)0x1000;
     {
       SubsysReco *G__Lpbase=(SubsysReco*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_PHG4SvtxTrackProjection),G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_SubsysReco),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       Fun4AllBase *G__Lpbase=(Fun4AllBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_PHG4SvtxTrackProjection),G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_Fun4AllBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablePHG4SvtxTrackProjection_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<float,SvtxTrackState*>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_maplEfloatcOSvtxTrackStatemUcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOSvtxTrackStatemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<float,SvtxTrackState*,less<float> >",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_maplEfloatcOSvtxTrackStatemUcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOSvtxTrackStatemUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<unsigned int>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<unsigned int,less<unsigned int> >",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SvtxTrack::CAL_LAYER>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlESvtxTrackcLcLCAL_LAYERcOallocatorlESvtxTrackcLcLCAL_LAYERgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlESvtxTrackcLcLCAL_LAYERcOallocatorlESvtxTrackcLcLCAL_LAYERgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlESvtxTrackcLcLCAL_LAYERcOallocatorlESvtxTrackcLcLCAL_LAYERgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlESvtxTrackcLcLCAL_LAYERcOallocatorlESvtxTrackcLcLCAL_LAYERgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlESvtxTrackcLcLCAL_LAYERcOallocatorlESvtxTrackcLcLCAL_LAYERgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PHG4SvtxTrackProjection */
static void G__setup_memvarPHG4SvtxTrackProjection(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_PHG4SvtxTrackProjection));
   { PHG4SvtxTrackProjection *p; p=(PHG4SvtxTrackProjection*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_PHG4HoughTransform),-1,-1,4,"_hough=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_num_cal_layers=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlESvtxTrackcLcLCAL_LAYERcOallocatorlESvtxTrackcLcLCAL_LAYERgRsPgR),G__defined_typename("vector<SvtxTrack::CAL_LAYER>"),-1,4,"_cal_types=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,4,"_cal_names=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"_cal_radii=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_magfield=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_mag_extent=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarPHG4SvtxTrackProjection_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPHG4SvtxTrackProjection(void) {
   /* PHG4SvtxTrackProjection */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_PHG4SvtxTrackProjection));
   G__memfunc_setup("PHG4SvtxTrackProjection",2266,G__PHG4SvtxTrackProjection_Dict_501_0_1, 105, G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_PHG4SvtxTrackProjection), -1, 0, 1, 1, 1, 0, "u 'string' - 11 '\"PHG4SvtxTrackProjection\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitRun",713,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("process_event",1408,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("End",279,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_mag_field",1335,G__PHG4SvtxTrackProjection_Dict_501_0_6, 102, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_mag_field",1347,G__PHG4SvtxTrackProjection_Dict_501_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - magfield", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("PHG4SvtxTrackProjection", 2266, G__PHG4SvtxTrackProjection_Dict_501_0_8, (int) ('i'), 
G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_PHG4SvtxTrackProjection), -1, 0, 1, 1, 1, 0, "u 'PHG4SvtxTrackProjection' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PHG4SvtxTrackProjection", 2392, G__PHG4SvtxTrackProjection_Dict_501_0_9, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__PHG4SvtxTrackProjection_Dict_501_0_10, (int) ('u'), G__get_linked_tagnum(&G__PHG4SvtxTrackProjection_DictLN_PHG4SvtxTrackProjection), -1, 1, 1, 1, 1, 0, "u 'PHG4SvtxTrackProjection' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncPHG4SvtxTrackProjection_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalPHG4SvtxTrackProjection_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcPHG4SvtxTrackProjection_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_Fun4AllBase = { "Fun4AllBase" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_PHCompositeNode = { "PHCompositeNode" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_SubsysReco = { "SubsysReco" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_PHG4HoughTransform = { "PHG4HoughTransform" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_maplEfloatcOSvtxTrackStatemUcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOSvtxTrackStatemUgRsPgRsPgR = { "map<float,SvtxTrackState*,less<float>,allocator<pair<const float,SvtxTrackState*> > >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR = { "set<unsigned int,less<unsigned int>,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_PHG4SvtxTrackProjection = { "PHG4SvtxTrackProjection" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_vectorlESvtxTrackcLcLCAL_LAYERcOallocatorlESvtxTrackcLcLCAL_LAYERgRsPgR = { "vector<SvtxTrack::CAL_LAYER,allocator<SvtxTrack::CAL_LAYER> >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlESvtxTrackcLcLCAL_LAYERcOallocatorlESvtxTrackcLcLCAL_LAYERgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SvtxTrack::CAL_LAYER,allocator<SvtxTrack::CAL_LAYER> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablePHG4SvtxTrackProjection_Dict() {
  G__PHG4SvtxTrackProjection_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_string.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_Fun4AllBase.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_PHCompositeNode.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_SubsysReco.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_PHG4HoughTransform.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_maplEfloatcOSvtxTrackStatemUcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOSvtxTrackStatemUgRsPgRsPgR.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_PHG4SvtxTrackProjection.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_vectorlESvtxTrackcLcLCAL_LAYERcOallocatorlESvtxTrackcLcLCAL_LAYERgRsPgR.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlESvtxTrackcLcLCAL_LAYERcOallocatorlESvtxTrackcLcLCAL_LAYERgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablePHG4SvtxTrackProjection_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_string);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_Fun4AllBase);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_PHCompositeNode);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_SubsysReco);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_PHG4HoughTransform);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_maplEfloatcOSvtxTrackStatemUcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOSvtxTrackStatemUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_PHG4SvtxTrackProjection),sizeof(PHG4SvtxTrackProjection),-1,197888,(char*)NULL,G__setup_memvarPHG4SvtxTrackProjection,G__setup_memfuncPHG4SvtxTrackProjection);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_vectorlESvtxTrackcLcLCAL_LAYERcOallocatorlESvtxTrackcLcLCAL_LAYERgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlESvtxTrackcLcLCAL_LAYERcOallocatorlESvtxTrackcLcLCAL_LAYERgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxTrackProjection_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupPHG4SvtxTrackProjection_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupPHG4SvtxTrackProjection_Dict()");
  G__set_cpp_environmentPHG4SvtxTrackProjection_Dict();
  G__cpp_setup_tagtablePHG4SvtxTrackProjection_Dict();

  G__cpp_setup_inheritancePHG4SvtxTrackProjection_Dict();

  G__cpp_setup_typetablePHG4SvtxTrackProjection_Dict();

  G__cpp_setup_memvarPHG4SvtxTrackProjection_Dict();

  G__cpp_setup_memfuncPHG4SvtxTrackProjection_Dict();
  G__cpp_setup_globalPHG4SvtxTrackProjection_Dict();
  G__cpp_setup_funcPHG4SvtxTrackProjection_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncPHG4SvtxTrackProjection_Dict();
  return;
}
class G__cpp_setup_initPHG4SvtxTrackProjection_Dict {
  public:
    G__cpp_setup_initPHG4SvtxTrackProjection_Dict() { G__add_setup_func("PHG4SvtxTrackProjection_Dict",(G__incsetup)(&G__cpp_setupPHG4SvtxTrackProjection_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initPHG4SvtxTrackProjection_Dict() { G__remove_setup_func("PHG4SvtxTrackProjection_Dict"); }
};
G__cpp_setup_initPHG4SvtxTrackProjection_Dict G__cpp_setup_initializerPHG4SvtxTrackProjection_Dict;

