//
// File generated by rootcint at Tue Mar 28 22:26:34 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME PHG4SvtxThresholds_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "PHG4SvtxThresholds_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void PHG4SvtxThresholds_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void PHG4SvtxThresholds_Dictionary();
   static void *new_PHG4SvtxThresholds(void *p = 0);
   static void *newArray_PHG4SvtxThresholds(Long_t size, void *p);
   static void delete_PHG4SvtxThresholds(void *p);
   static void deleteArray_PHG4SvtxThresholds(void *p);
   static void destruct_PHG4SvtxThresholds(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::PHG4SvtxThresholds*)
   {
      ::PHG4SvtxThresholds *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::PHG4SvtxThresholds),0);
      static ::ROOT::TGenericClassInfo 
         instance("PHG4SvtxThresholds", "./PHG4SvtxThresholds.h", 13,
                  typeid(::PHG4SvtxThresholds), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &PHG4SvtxThresholds_Dictionary, isa_proxy, 3,
                  sizeof(::PHG4SvtxThresholds) );
      instance.SetNew(&new_PHG4SvtxThresholds);
      instance.SetNewArray(&newArray_PHG4SvtxThresholds);
      instance.SetDelete(&delete_PHG4SvtxThresholds);
      instance.SetDeleteArray(&deleteArray_PHG4SvtxThresholds);
      instance.SetDestructor(&destruct_PHG4SvtxThresholds);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::PHG4SvtxThresholds*)
   {
      return GenerateInitInstanceLocal((::PHG4SvtxThresholds*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PHG4SvtxThresholds*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void PHG4SvtxThresholds_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::PHG4SvtxThresholds*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_PHG4SvtxThresholds(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PHG4SvtxThresholds : new ::PHG4SvtxThresholds;
   }
   static void *newArray_PHG4SvtxThresholds(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PHG4SvtxThresholds[nElements] : new ::PHG4SvtxThresholds[nElements];
   }
   // Wrapper around operator delete
   static void delete_PHG4SvtxThresholds(void *p) {
      delete ((::PHG4SvtxThresholds*)p);
   }
   static void deleteArray_PHG4SvtxThresholds(void *p) {
      delete [] ((::PHG4SvtxThresholds*)p);
   }
   static void destruct_PHG4SvtxThresholds(void *p) {
      typedef ::PHG4SvtxThresholds current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::PHG4SvtxThresholds

/********************************************************
* PHG4SvtxThresholds_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablePHG4SvtxThresholds_Dict();

extern "C" void G__set_cpp_environmentPHG4SvtxThresholds_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("PHG4SvtxThresholds.h");
  G__cpp_reset_tagtablePHG4SvtxThresholds_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevPHG4SvtxThresholds_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PHG4SvtxThresholds */
static int G__PHG4SvtxThresholds_Dict_441_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PHG4SvtxThresholds* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PHG4SvtxThresholds(*(string*) libp->para[0].ref);
     } else {
       p = new((void*) gvp) PHG4SvtxThresholds(*(string*) libp->para[0].ref);
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new PHG4SvtxThresholds[n];
       } else {
         p = new((void*) gvp) PHG4SvtxThresholds[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new PHG4SvtxThresholds;
       } else {
         p = new((void*) gvp) PHG4SvtxThresholds;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_PHG4SvtxThresholds));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4SvtxThresholds_Dict_441_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4SvtxThresholds*) G__getstructoffset())->set_threshold((const float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4SvtxThresholds_Dict_441_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4SvtxThresholds*) G__getstructoffset())->set_threshold((const int) G__int(libp->para[0]), (const float) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4SvtxThresholds_Dict_441_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const PHG4SvtxThresholds*) G__getstructoffset())->get_threshold_by_layer((const int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4SvtxThresholds_Dict_441_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4SvtxThresholds*) G__getstructoffset())->set_use_thickness_mip((const int) G__int(libp->para[0]), (const bool) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4SvtxThresholds_Dict_441_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((PHG4SvtxThresholds*) G__getstructoffset())->get_use_thickness_mip((const int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__PHG4SvtxThresholds_Dict_441_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   PHG4SvtxThresholds* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new PHG4SvtxThresholds(*(PHG4SvtxThresholds*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_PHG4SvtxThresholds));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PHG4SvtxThresholds G__TPHG4SvtxThresholds;
static int G__PHG4SvtxThresholds_Dict_441_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PHG4SvtxThresholds*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PHG4SvtxThresholds*) (soff+(sizeof(PHG4SvtxThresholds)*i)))->~G__TPHG4SvtxThresholds();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PHG4SvtxThresholds*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PHG4SvtxThresholds*) (soff))->~G__TPHG4SvtxThresholds();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__PHG4SvtxThresholds_Dict_441_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PHG4SvtxThresholds* dest = (PHG4SvtxThresholds*) G__getstructoffset();
   *dest = *(PHG4SvtxThresholds*) libp->para[0].ref;
   const PHG4SvtxThresholds& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PHG4SvtxThresholds */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncPHG4SvtxThresholds_Dict {
 public:
  G__Sizep2memfuncPHG4SvtxThresholds_Dict(): p(&G__Sizep2memfuncPHG4SvtxThresholds_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncPHG4SvtxThresholds_Dict::*p)();
};

size_t G__get_sizep2memfuncPHG4SvtxThresholds_Dict()
{
  G__Sizep2memfuncPHG4SvtxThresholds_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancePHG4SvtxThresholds_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_PHG4SvtxThresholds))) {
     PHG4SvtxThresholds *G__Lderived;
     G__Lderived=(PHG4SvtxThresholds*)0x1000;
     {
       SubsysReco *G__Lpbase=(SubsysReco*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_PHG4SvtxThresholds),G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_SubsysReco),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       Fun4AllBase *G__Lpbase=(Fun4AllBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_PHG4SvtxThresholds),G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_Fun4AllBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablePHG4SvtxThresholds_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,timer>",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,timer>",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,PHTimeServer::timer>",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,PHTimeServer::timer,less<string> >",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,float>",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,float,less<int> >",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,bool>",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_maplEintcOboolcOlesslEintgRcOallocatorlEpairlEconstsPintcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,bool,less<int> >",117,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_maplEintcOboolcOlesslEintgRcOallocatorlEpairlEconstsPintcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PHG4SvtxThresholds */
static void G__setup_memvarPHG4SvtxThresholds(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_PHG4SvtxThresholds));
   { PHG4SvtxThresholds *p; p=(PHG4SvtxThresholds*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR),G__defined_typename("map<int,float>"),-1,4,"_fraction_of_mip=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR),G__defined_typename("map<int,float>"),-1,4,"_thresholds_by_layer=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_maplEintcOboolcOlesslEintgRcOallocatorlEpairlEconstsPintcOboolgRsPgRsPgR),G__defined_typename("map<int,bool>"),-1,4,"_use_thickness_mip=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_SvtxHitMap),-1,-1,4,"_hits=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_PHTimeServercLcLtimer),-1,-1,4,"_timer=",0,"/< Timer");
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarPHG4SvtxThresholds_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPHG4SvtxThresholds(void) {
   /* PHG4SvtxThresholds */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_PHG4SvtxThresholds));
   G__memfunc_setup("PHG4SvtxThresholds",1768,G__PHG4SvtxThresholds_Dict_441_0_1, 105, G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_PHG4SvtxThresholds), -1, 0, 1, 1, 1, 0, "u 'string' - 11 '\"PHG4SvtxThresholds\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitRun",713,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("process_event",1408,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("End",279,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_threshold",1400,G__PHG4SvtxThresholds_Dict_441_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 10 - fraction_of_mip", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_threshold",1400,G__PHG4SvtxThresholds_Dict_441_0_7, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 10 - layer f - - 10 - fraction_of_mip", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_threshold_by_layer",2338,G__PHG4SvtxThresholds_Dict_441_0_8, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 10 - layer", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_use_thickness_mip",2248,G__PHG4SvtxThresholds_Dict_441_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 10 - layer g - - 10 - use_thickness_mip", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_use_thickness_mip",2236,G__PHG4SvtxThresholds_Dict_441_0_10, 103, -1, -1, 0, 1, 1, 1, 0, "i - - 10 - layer", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateCylinderThresholds",2792,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateLadderThresholds",2554,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CalculateMapsLadderThresholds",2955,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("PHG4SvtxThresholds", 1768, G__PHG4SvtxThresholds_Dict_441_0_14, (int) ('i'), G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_PHG4SvtxThresholds), -1, 0, 1, 1, 1, 0, "u 'PHG4SvtxThresholds' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PHG4SvtxThresholds", 1894, G__PHG4SvtxThresholds_Dict_441_0_15, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__PHG4SvtxThresholds_Dict_441_0_16, (int) ('u'), G__get_linked_tagnum(&G__PHG4SvtxThresholds_DictLN_PHG4SvtxThresholds), -1, 1, 1, 1, 1, 0, "u 'PHG4SvtxThresholds' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncPHG4SvtxThresholds_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalPHG4SvtxThresholds_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcPHG4SvtxThresholds_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_Fun4AllBase = { "Fun4AllBase" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_PHCompositeNode = { "PHCompositeNode" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_SubsysReco = { "SubsysReco" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_PHTimeServer = { "PHTimeServer" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_PHTimeServercLcLtimer = { "PHTimeServer::timer" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR = { "map<string,PHTimeServer::timer,less<string>,allocator<pair<const string,PHTimeServer::timer> > >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_SvtxHitMap = { "SvtxHitMap" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_PHG4SvtxThresholds = { "PHG4SvtxThresholds" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR = { "map<int,float,less<int>,allocator<pair<const int,float> > >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxThresholds_DictLN_maplEintcOboolcOlesslEintgRcOallocatorlEpairlEconstsPintcOboolgRsPgRsPgR = { "map<int,bool,less<int>,allocator<pair<const int,bool> > >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablePHG4SvtxThresholds_Dict() {
  G__PHG4SvtxThresholds_DictLN_string.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_Fun4AllBase.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_PHCompositeNode.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_SubsysReco.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_PHTimeServer.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_PHTimeServercLcLtimer.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_SvtxHitMap.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_PHG4SvtxThresholds.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR.tagnum = -1 ;
  G__PHG4SvtxThresholds_DictLN_maplEintcOboolcOlesslEintgRcOallocatorlEpairlEconstsPintcOboolgRsPgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablePHG4SvtxThresholds_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_string);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_Fun4AllBase);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_PHCompositeNode);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_SubsysReco);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_PHTimeServer);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_PHTimeServercLcLtimer);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_SvtxHitMap);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_PHG4SvtxThresholds),sizeof(PHG4SvtxThresholds),-1,197888,(char*)NULL,G__setup_memvarPHG4SvtxThresholds,G__setup_memfuncPHG4SvtxThresholds);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxThresholds_DictLN_maplEintcOboolcOlesslEintgRcOallocatorlEpairlEconstsPintcOboolgRsPgRsPgR);
}
extern "C" void G__cpp_setupPHG4SvtxThresholds_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupPHG4SvtxThresholds_Dict()");
  G__set_cpp_environmentPHG4SvtxThresholds_Dict();
  G__cpp_setup_tagtablePHG4SvtxThresholds_Dict();

  G__cpp_setup_inheritancePHG4SvtxThresholds_Dict();

  G__cpp_setup_typetablePHG4SvtxThresholds_Dict();

  G__cpp_setup_memvarPHG4SvtxThresholds_Dict();

  G__cpp_setup_memfuncPHG4SvtxThresholds_Dict();
  G__cpp_setup_globalPHG4SvtxThresholds_Dict();
  G__cpp_setup_funcPHG4SvtxThresholds_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncPHG4SvtxThresholds_Dict();
  return;
}
class G__cpp_setup_initPHG4SvtxThresholds_Dict {
  public:
    G__cpp_setup_initPHG4SvtxThresholds_Dict() { G__add_setup_func("PHG4SvtxThresholds_Dict",(G__incsetup)(&G__cpp_setupPHG4SvtxThresholds_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initPHG4SvtxThresholds_Dict() { G__remove_setup_func("PHG4SvtxThresholds_Dict"); }
};
G__cpp_setup_initPHG4SvtxThresholds_Dict G__cpp_setup_initializerPHG4SvtxThresholds_Dict;

