//
// File generated by rootcint at Tue Mar 28 22:44:55 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME PHG4SvtxBeamSpotReco_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "PHG4SvtxBeamSpotReco_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void PHG4SvtxBeamSpotReco_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void PHG4SvtxBeamSpotReco_Dictionary();
   static void *new_PHG4SvtxBeamSpotReco(void *p = 0);
   static void *newArray_PHG4SvtxBeamSpotReco(Long_t size, void *p);
   static void delete_PHG4SvtxBeamSpotReco(void *p);
   static void deleteArray_PHG4SvtxBeamSpotReco(void *p);
   static void destruct_PHG4SvtxBeamSpotReco(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::PHG4SvtxBeamSpotReco*)
   {
      ::PHG4SvtxBeamSpotReco *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::PHG4SvtxBeamSpotReco),0);
      static ::ROOT::TGenericClassInfo 
         instance("PHG4SvtxBeamSpotReco", "./PHG4SvtxBeamSpotReco.h", 13,
                  typeid(::PHG4SvtxBeamSpotReco), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &PHG4SvtxBeamSpotReco_Dictionary, isa_proxy, 3,
                  sizeof(::PHG4SvtxBeamSpotReco) );
      instance.SetNew(&new_PHG4SvtxBeamSpotReco);
      instance.SetNewArray(&newArray_PHG4SvtxBeamSpotReco);
      instance.SetDelete(&delete_PHG4SvtxBeamSpotReco);
      instance.SetDeleteArray(&deleteArray_PHG4SvtxBeamSpotReco);
      instance.SetDestructor(&destruct_PHG4SvtxBeamSpotReco);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::PHG4SvtxBeamSpotReco*)
   {
      return GenerateInitInstanceLocal((::PHG4SvtxBeamSpotReco*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PHG4SvtxBeamSpotReco*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void PHG4SvtxBeamSpotReco_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::PHG4SvtxBeamSpotReco*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_PHG4SvtxBeamSpotReco(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PHG4SvtxBeamSpotReco : new ::PHG4SvtxBeamSpotReco;
   }
   static void *newArray_PHG4SvtxBeamSpotReco(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PHG4SvtxBeamSpotReco[nElements] : new ::PHG4SvtxBeamSpotReco[nElements];
   }
   // Wrapper around operator delete
   static void delete_PHG4SvtxBeamSpotReco(void *p) {
      delete ((::PHG4SvtxBeamSpotReco*)p);
   }
   static void deleteArray_PHG4SvtxBeamSpotReco(void *p) {
      delete [] ((::PHG4SvtxBeamSpotReco*)p);
   }
   static void destruct_PHG4SvtxBeamSpotReco(void *p) {
      typedef ::PHG4SvtxBeamSpotReco current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::PHG4SvtxBeamSpotReco

/********************************************************
* PHG4SvtxBeamSpotReco_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablePHG4SvtxBeamSpotReco_Dict();

extern "C" void G__set_cpp_environmentPHG4SvtxBeamSpotReco_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("PHG4SvtxBeamSpotReco.h");
  G__cpp_reset_tagtablePHG4SvtxBeamSpotReco_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevPHG4SvtxBeamSpotReco_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PHG4SvtxBeamSpotReco */
static int G__PHG4SvtxBeamSpotReco_Dict_532_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PHG4SvtxBeamSpotReco* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PHG4SvtxBeamSpotReco(*(string*) libp->para[0].ref);
     } else {
       p = new((void*) gvp) PHG4SvtxBeamSpotReco(*(string*) libp->para[0].ref);
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new PHG4SvtxBeamSpotReco[n];
       } else {
         p = new((void*) gvp) PHG4SvtxBeamSpotReco[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new PHG4SvtxBeamSpotReco;
       } else {
         p = new((void*) gvp) PHG4SvtxBeamSpotReco;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_PHG4SvtxBeamSpotReco));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__PHG4SvtxBeamSpotReco_Dict_532_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   PHG4SvtxBeamSpotReco* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new PHG4SvtxBeamSpotReco(*(PHG4SvtxBeamSpotReco*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_PHG4SvtxBeamSpotReco));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PHG4SvtxBeamSpotReco G__TPHG4SvtxBeamSpotReco;
static int G__PHG4SvtxBeamSpotReco_Dict_532_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PHG4SvtxBeamSpotReco*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PHG4SvtxBeamSpotReco*) (soff+(sizeof(PHG4SvtxBeamSpotReco)*i)))->~G__TPHG4SvtxBeamSpotReco();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PHG4SvtxBeamSpotReco*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PHG4SvtxBeamSpotReco*) (soff))->~G__TPHG4SvtxBeamSpotReco();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PHG4SvtxBeamSpotReco */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncPHG4SvtxBeamSpotReco_Dict {
 public:
  G__Sizep2memfuncPHG4SvtxBeamSpotReco_Dict(): p(&G__Sizep2memfuncPHG4SvtxBeamSpotReco_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncPHG4SvtxBeamSpotReco_Dict::*p)();
};

size_t G__get_sizep2memfuncPHG4SvtxBeamSpotReco_Dict()
{
  G__Sizep2memfuncPHG4SvtxBeamSpotReco_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancePHG4SvtxBeamSpotReco_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_PHG4SvtxBeamSpotReco))) {
     PHG4SvtxBeamSpotReco *G__Lderived;
     G__Lderived=(PHG4SvtxBeamSpotReco*)0x1000;
     {
       SubsysReco *G__Lpbase=(SubsysReco*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_PHG4SvtxBeamSpotReco),G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_SubsysReco),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       Fun4AllBase *G__Lpbase=(Fun4AllBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_PHG4SvtxBeamSpotReco),G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_Fun4AllBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablePHG4SvtxBeamSpotReco_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,timer>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,timer>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,PHTimeServer::timer>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,PHTimeServer::timer,less<string> >",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PHG4SvtxBeamSpotReco */
static void G__setup_memvarPHG4SvtxBeamSpotReco(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_PHG4SvtxBeamSpotReco));
   { PHG4SvtxBeamSpotReco *p; p=(PHG4SvtxBeamSpotReco*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_TPrincipal),-1,-1,4,"_pca=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_SvtxVertexMap),-1,-1,4,"_vertexes=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_SvtxBeamSpot),-1,-1,4,"_beamspot=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_PHTimeServercLcLtimer),-1,-1,4,"_timer=",0,"/< Timer");
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarPHG4SvtxBeamSpotReco_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPHG4SvtxBeamSpotReco(void) {
   /* PHG4SvtxBeamSpotReco */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_PHG4SvtxBeamSpotReco));
   G__memfunc_setup("PHG4SvtxBeamSpotReco",1900,G__PHG4SvtxBeamSpotReco_Dict_532_0_1, 105, G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_PHG4SvtxBeamSpotReco), -1, 0, 1, 1, 1, 0, "u 'string' - 11 '\"PHG4SvtxBeamSpotReco\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitRun",713,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("process_event",1408,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("End",279,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   // automatic copy constructor
   G__memfunc_setup("PHG4SvtxBeamSpotReco", 1900, G__PHG4SvtxBeamSpotReco_Dict_532_0_6, (int) ('i'), G__get_linked_tagnum(&G__PHG4SvtxBeamSpotReco_DictLN_PHG4SvtxBeamSpotReco), -1, 0, 1, 1, 1, 0, "u 'PHG4SvtxBeamSpotReco' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PHG4SvtxBeamSpotReco", 2026, G__PHG4SvtxBeamSpotReco_Dict_532_0_7, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncPHG4SvtxBeamSpotReco_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalPHG4SvtxBeamSpotReco_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcPHG4SvtxBeamSpotReco_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_Fun4AllBase = { "Fun4AllBase" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_PHCompositeNode = { "PHCompositeNode" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_SubsysReco = { "SubsysReco" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_PHTimeServer = { "PHTimeServer" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_PHTimeServercLcLtimer = { "PHTimeServer::timer" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR = { "map<string,PHTimeServer::timer,less<string>,allocator<pair<const string,PHTimeServer::timer> > >" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TPrincipal = { "TPrincipal" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_SvtxBeamSpot = { "SvtxBeamSpot" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_SvtxVertexMap = { "SvtxVertexMap" , 99 , -1 };
G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_PHG4SvtxBeamSpotReco = { "PHG4SvtxBeamSpotReco" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablePHG4SvtxBeamSpotReco_Dict() {
  G__PHG4SvtxBeamSpotReco_DictLN_string.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_Fun4AllBase.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_PHCompositeNode.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_SubsysReco.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_PHTimeServer.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_PHTimeServercLcLtimer.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_TPrincipal.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_SvtxBeamSpot.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_SvtxVertexMap.tagnum = -1 ;
  G__PHG4SvtxBeamSpotReco_DictLN_PHG4SvtxBeamSpotReco.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablePHG4SvtxBeamSpotReco_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_string);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_Fun4AllBase);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_PHCompositeNode);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_SubsysReco);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_PHTimeServer);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_PHTimeServercLcLtimer);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_TPrincipal);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_SvtxBeamSpot);
   G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_SvtxVertexMap);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PHG4SvtxBeamSpotReco_DictLN_PHG4SvtxBeamSpotReco),sizeof(PHG4SvtxBeamSpotReco),-1,197888,(char*)NULL,G__setup_memvarPHG4SvtxBeamSpotReco,G__setup_memfuncPHG4SvtxBeamSpotReco);
}
extern "C" void G__cpp_setupPHG4SvtxBeamSpotReco_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupPHG4SvtxBeamSpotReco_Dict()");
  G__set_cpp_environmentPHG4SvtxBeamSpotReco_Dict();
  G__cpp_setup_tagtablePHG4SvtxBeamSpotReco_Dict();

  G__cpp_setup_inheritancePHG4SvtxBeamSpotReco_Dict();

  G__cpp_setup_typetablePHG4SvtxBeamSpotReco_Dict();

  G__cpp_setup_memvarPHG4SvtxBeamSpotReco_Dict();

  G__cpp_setup_memfuncPHG4SvtxBeamSpotReco_Dict();
  G__cpp_setup_globalPHG4SvtxBeamSpotReco_Dict();
  G__cpp_setup_funcPHG4SvtxBeamSpotReco_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncPHG4SvtxBeamSpotReco_Dict();
  return;
}
class G__cpp_setup_initPHG4SvtxBeamSpotReco_Dict {
  public:
    G__cpp_setup_initPHG4SvtxBeamSpotReco_Dict() { G__add_setup_func("PHG4SvtxBeamSpotReco_Dict",(G__incsetup)(&G__cpp_setupPHG4SvtxBeamSpotReco_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initPHG4SvtxBeamSpotReco_Dict() { G__remove_setup_func("PHG4SvtxBeamSpotReco_Dict"); }
};
G__cpp_setup_initPHG4SvtxBeamSpotReco_Dict G__cpp_setup_initializerPHG4SvtxBeamSpotReco_Dict;

