//
// File generated by rootcint at Tue Mar 28 22:26:41 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME PHG4HoughTransformTPC_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "PHG4HoughTransformTPC_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void PHG4HoughTransformTPC_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void PHG4HoughTransformTPC_Dictionary();
   static void *new_PHG4HoughTransformTPC(void *p = 0);
   static void *newArray_PHG4HoughTransformTPC(Long_t size, void *p);
   static void delete_PHG4HoughTransformTPC(void *p);
   static void deleteArray_PHG4HoughTransformTPC(void *p);
   static void destruct_PHG4HoughTransformTPC(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::PHG4HoughTransformTPC*)
   {
      ::PHG4HoughTransformTPC *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::PHG4HoughTransformTPC),0);
      static ::ROOT::TGenericClassInfo 
         instance("PHG4HoughTransformTPC", "./PHG4HoughTransformTPC.h", 55,
                  typeid(::PHG4HoughTransformTPC), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &PHG4HoughTransformTPC_Dictionary, isa_proxy, 3,
                  sizeof(::PHG4HoughTransformTPC) );
      instance.SetNew(&new_PHG4HoughTransformTPC);
      instance.SetNewArray(&newArray_PHG4HoughTransformTPC);
      instance.SetDelete(&delete_PHG4HoughTransformTPC);
      instance.SetDeleteArray(&deleteArray_PHG4HoughTransformTPC);
      instance.SetDestructor(&destruct_PHG4HoughTransformTPC);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::PHG4HoughTransformTPC*)
   {
      return GenerateInitInstanceLocal((::PHG4HoughTransformTPC*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PHG4HoughTransformTPC*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void PHG4HoughTransformTPC_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::PHG4HoughTransformTPC*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_PHG4HoughTransformTPC(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PHG4HoughTransformTPC : new ::PHG4HoughTransformTPC;
   }
   static void *newArray_PHG4HoughTransformTPC(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PHG4HoughTransformTPC[nElements] : new ::PHG4HoughTransformTPC[nElements];
   }
   // Wrapper around operator delete
   static void delete_PHG4HoughTransformTPC(void *p) {
      delete ((::PHG4HoughTransformTPC*)p);
   }
   static void deleteArray_PHG4HoughTransformTPC(void *p) {
      delete [] ((::PHG4HoughTransformTPC*)p);
   }
   static void destruct_PHG4HoughTransformTPC(void *p) {
      typedef ::PHG4HoughTransformTPC current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::PHG4HoughTransformTPC

/********************************************************
* PHG4HoughTransformTPC_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablePHG4HoughTransformTPC_Dict();

extern "C" void G__set_cpp_environmentPHG4HoughTransformTPC_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("PHG4HoughTransformTPC.h");
  G__cpp_reset_tagtablePHG4HoughTransformTPC_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevPHG4HoughTransformTPC_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PHG4HoughTransformTPC */
static int G__PHG4HoughTransformTPC_Dict_504_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PHG4HoughTransformTPC* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PHG4HoughTransformTPC(
(unsigned int) G__int(libp->para[0]), (unsigned int) G__int(libp->para[1])
, *(string*) libp->para[2].ref);
     } else {
       p = new((void*) gvp) PHG4HoughTransformTPC(
(unsigned int) G__int(libp->para[0]), (unsigned int) G__int(libp->para[1])
, *(string*) libp->para[2].ref);
     }
     break;
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PHG4HoughTransformTPC((unsigned int) G__int(libp->para[0]), (unsigned int) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) PHG4HoughTransformTPC((unsigned int) G__int(libp->para[0]), (unsigned int) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PHG4HoughTransformTPC((unsigned int) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) PHG4HoughTransformTPC((unsigned int) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new PHG4HoughTransformTPC[n];
       } else {
         p = new((void*) gvp) PHG4HoughTransformTPC[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new PHG4HoughTransformTPC;
       } else {
         p = new((void*) gvp) PHG4HoughTransformTPC;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_PHG4HoughTransformTPC));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->Verbosity((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      PHG4HoughTransformTPC::projectToRadius((SvtxTrack*) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), *(vector<double>*) libp->para[3].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      PHG4HoughTransformTPC::projectToRadius((SvtxTrackState*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, *(vector<double>*) libp->para[4].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const PHG4HoughTransformTPC*) G__getstructoffset())->get_mag_field());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->set_mag_field((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      ((PHG4HoughTransformTPC*) G__getstructoffset())->set_chi2_cut_fast((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ((PHG4HoughTransformTPC*) G__getstructoffset())->set_chi2_cut_fast((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((PHG4HoughTransformTPC*) G__getstructoffset())->set_chi2_cut_fast((double) G__double(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->set_chi2_cut_init((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PHG4HoughTransformTPC*) G__getstructoffset())->get_chi2_cut_init());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->set_chi2_cut_full((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PHG4HoughTransformTPC*) G__getstructoffset())->get_chi2_cut_full());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->set_ca_chi2_cut((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PHG4HoughTransformTPC*) G__getstructoffset())->get_ca_chi2_cut());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->set_cos_angle_cut((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((PHG4HoughTransformTPC*) G__getstructoffset())->get_cos_angle_cut());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->set_min_pT((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->set_z0_range((float) G__double(libp->para[0]), (float) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->set_d_max((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->set_material((int) G__int(libp->para[0]), (float) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->set_use_vertex((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->setRejectGhosts((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->setRemoveHits((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->setUseCellSize((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->setMaxClusterError((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->setBinScale((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->setZBinScale((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->setCutOnDCA((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->setDCACut((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->setDCAZCut((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->setPtRescaleFactor((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->setVoteErrorScale((unsigned int) G__int(libp->para[0]), (float) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->setFitErrorScale((unsigned int) G__int(libp->para[0]), (float) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4HoughTransformTPC_Dict_504_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4HoughTransformTPC*) G__getstructoffset())->setWriteRecoTree((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__PHG4HoughTransformTPC_Dict_504_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   PHG4HoughTransformTPC* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new PHG4HoughTransformTPC(*(PHG4HoughTransformTPC*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_PHG4HoughTransformTPC));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PHG4HoughTransformTPC G__TPHG4HoughTransformTPC;
static int G__PHG4HoughTransformTPC_Dict_504_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PHG4HoughTransformTPC*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PHG4HoughTransformTPC*) (soff+(sizeof(PHG4HoughTransformTPC)*i)))->~G__TPHG4HoughTransformTPC();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PHG4HoughTransformTPC*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PHG4HoughTransformTPC*) (soff))->~G__TPHG4HoughTransformTPC();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__PHG4HoughTransformTPC_Dict_504_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PHG4HoughTransformTPC* dest = (PHG4HoughTransformTPC*) G__getstructoffset();
   *dest = *(PHG4HoughTransformTPC*) libp->para[0].ref;
   const PHG4HoughTransformTPC& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PHG4HoughTransformTPC */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncPHG4HoughTransformTPC_Dict {
 public:
  G__Sizep2memfuncPHG4HoughTransformTPC_Dict(): p(&G__Sizep2memfuncPHG4HoughTransformTPC_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncPHG4HoughTransformTPC_Dict::*p)();
};

size_t G__get_sizep2memfuncPHG4HoughTransformTPC_Dict()
{
  G__Sizep2memfuncPHG4HoughTransformTPC_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancePHG4HoughTransformTPC_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_PHG4HoughTransformTPC))) {
     PHG4HoughTransformTPC *G__Lderived;
     G__Lderived=(PHG4HoughTransformTPC*)0x1000;
     {
       SubsysReco *G__Lpbase=(SubsysReco*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_PHG4HoughTransformTPC),G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_SubsysReco),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       Fun4AllBase *G__Lpbase=(Fun4AllBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_PHG4HoughTransformTPC),G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_Fun4AllBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablePHG4HoughTransformTPC_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,timer>",117,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,timer>",117,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,PHTimeServer::timer>",117,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,PHTimeServer::timer,less<string> >",117,G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PHG4HoughTransformTPC */
static void G__setup_memvarPHG4HoughTransformTPC(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_PHG4HoughTransformTPC));
   { PHG4HoughTransformTPC *p; p=(PHG4HoughTransformTPC*)0x1000; if (p) { }
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarPHG4HoughTransformTPC_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPHG4HoughTransformTPC(void) {
   /* PHG4HoughTransformTPC */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_PHG4HoughTransformTPC));
   G__memfunc_setup("PHG4HoughTransformTPC",1969,G__PHG4HoughTransformTPC_Dict_504_0_1, 105, G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_PHG4HoughTransformTPC), -1, 0, 3, 1, 1, 0, 
"h - - 0 '4' seed_layers h - - 0 '4' req_seed "
"u 'string' - 11 '\"PHG4HoughTransformTPC\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitRun",713,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("process_event",1408,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("End",279,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - topNode", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Verbosity",967,G__PHG4HoughTransformTPC_Dict_504_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - verb", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("projectToRadius",1570,G__PHG4HoughTransformTPC_Dict_504_0_7, 121, -1, -1, 0, 4, 3, 1, 0, 
"U 'SvtxTrack' - 10 - track d - - 0 - magfield "
"d - - 0 - radius u 'vector<double,allocator<double> >' 'vector<double>' 1 - intersection", (char*)NULL, (void*) G__func2void( (void (*)(const SvtxTrack*, double, double, vector<double>&))(&PHG4HoughTransformTPC::projectToRadius) ), 0);
   G__memfunc_setup("projectToRadius",1570,G__PHG4HoughTransformTPC_Dict_504_0_8, 121, -1, -1, 0, 5, 3, 1, 0, 
"U 'SvtxTrackState' - 10 - state i - - 0 - charge "
"d - - 0 - magfield d - - 0 - radius "
"u 'vector<double,allocator<double> >' 'vector<double>' 1 - intersection", (char*)NULL, (void*) G__func2void( (void (*)(const SvtxTrackState*, int, double, double, vector<double>&))(&PHG4HoughTransformTPC::projectToRadius) ), 0);
   G__memfunc_setup("get_mag_field",1335,G__PHG4HoughTransformTPC_Dict_504_0_9, 102, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_mag_field",1347,G__PHG4HoughTransformTPC_Dict_504_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - magField", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_chi2_cut_fast",1737,G__PHG4HoughTransformTPC_Dict_504_0_11, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - - 0 - cut_par0 d - - 0 '0.0' cut_par1 "
"d - - 0 'FLT_MAX' cut_max", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_chi2_cut_init",1743,G__PHG4HoughTransformTPC_Dict_504_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - chi2_cut_init", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_chi2_cut_init",1731,G__PHG4HoughTransformTPC_Dict_504_0_13, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_chi2_cut_full",1742,G__PHG4HoughTransformTPC_Dict_504_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - chi2_cut", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_chi2_cut_full",1730,G__PHG4HoughTransformTPC_Dict_504_0_15, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_ca_chi2_cut",1503,G__PHG4HoughTransformTPC_Dict_504_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - chi2_cut", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_ca_chi2_cut",1491,G__PHG4HoughTransformTPC_Dict_504_0_17, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_cos_angle_cut",1793,G__PHG4HoughTransformTPC_Dict_504_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - cos_angle_cut", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_cos_angle_cut",1781,G__PHG4HoughTransformTPC_Dict_504_0_19, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_min_pT",1042,G__PHG4HoughTransformTPC_Dict_504_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - pt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_z0_range",1217,G__PHG4HoughTransformTPC_Dict_504_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"f - - 0 - min_z0 f - - 0 - max_z0", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_d_max",948,G__PHG4HoughTransformTPC_Dict_504_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - max_d", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_material",1274,G__PHG4HoughTransformTPC_Dict_504_0_23, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - layer f - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_use_vertex",1525,G__PHG4HoughTransformTPC_Dict_504_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - ub", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setRejectGhosts",1569,G__PHG4HoughTransformTPC_Dict_504_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - rg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setRemoveHits",1362,G__PHG4HoughTransformTPC_Dict_504_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - rh", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setUseCellSize",1428,G__PHG4HoughTransformTPC_Dict_504_0_27, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - use_cell_size", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setMaxClusterError",1886,G__PHG4HoughTransformTPC_Dict_504_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - max_cluster_error", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setBinScale",1101,G__PHG4HoughTransformTPC_Dict_504_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - scale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setZBinScale",1191,G__PHG4HoughTransformTPC_Dict_504_0_30, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - scale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setCutOnDCA",1021,G__PHG4HoughTransformTPC_Dict_504_0_31, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - cod", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setDCACut",832,G__PHG4HoughTransformTPC_Dict_504_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - dcut", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setDCAZCut",922,G__PHG4HoughTransformTPC_Dict_504_0_33, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - dzcut", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setPtRescaleFactor",1838,G__PHG4HoughTransformTPC_Dict_504_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - pt_rescale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setVoteErrorScale",1756,G__PHG4HoughTransformTPC_Dict_504_0_35, 121, -1, -1, 0, 2, 1, 1, 0, 
"h - - 0 - layer f - - 0 - scale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setFitErrorScale",1633,G__PHG4HoughTransformTPC_Dict_504_0_36, 121, -1, -1, 0, 2, 1, 1, 0, 
"h - - 0 - layer f - - 0 - scale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("setWriteRecoTree",1648,G__PHG4HoughTransformTPC_Dict_504_0_37, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - flag", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("PHG4HoughTransformTPC", 1969, G__PHG4HoughTransformTPC_Dict_504_0_38, (int) ('i'), 
G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_PHG4HoughTransformTPC), -1, 0, 1, 1, 1, 0, "u 'PHG4HoughTransformTPC' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PHG4HoughTransformTPC", 2095, G__PHG4HoughTransformTPC_Dict_504_0_39, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__PHG4HoughTransformTPC_Dict_504_0_40, (int) ('u'), G__get_linked_tagnum(&G__PHG4HoughTransformTPC_DictLN_PHG4HoughTransformTPC), -1, 1, 1, 1, 1, 0, "u 'PHG4HoughTransformTPC' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncPHG4HoughTransformTPC_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalPHG4HoughTransformTPC_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcPHG4HoughTransformTPC_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__PHG4HoughTransformTPC_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__PHG4HoughTransformTPC_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__PHG4HoughTransformTPC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__PHG4HoughTransformTPC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4HoughTransformTPC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__PHG4HoughTransformTPC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4HoughTransformTPC_DictLN_Fun4AllBase = { "Fun4AllBase" , 99 , -1 };
G__linked_taginfo G__PHG4HoughTransformTPC_DictLN_PHCompositeNode = { "PHCompositeNode" , 99 , -1 };
G__linked_taginfo G__PHG4HoughTransformTPC_DictLN_SubsysReco = { "SubsysReco" , 99 , -1 };
G__linked_taginfo G__PHG4HoughTransformTPC_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR = { "map<string,PHTimeServer::timer,less<string>,allocator<pair<const string,PHTimeServer::timer> > >" , 99 , -1 };
G__linked_taginfo G__PHG4HoughTransformTPC_DictLN_SvtxTrack = { "SvtxTrack" , 99 , -1 };
G__linked_taginfo G__PHG4HoughTransformTPC_DictLN_SvtxTrackState = { "SvtxTrackState" , 99 , -1 };
G__linked_taginfo G__PHG4HoughTransformTPC_DictLN_PHG4HoughTransformTPC = { "PHG4HoughTransformTPC" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablePHG4HoughTransformTPC_Dict() {
  G__PHG4HoughTransformTPC_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__PHG4HoughTransformTPC_DictLN_string.tagnum = -1 ;
  G__PHG4HoughTransformTPC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__PHG4HoughTransformTPC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4HoughTransformTPC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__PHG4HoughTransformTPC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4HoughTransformTPC_DictLN_Fun4AllBase.tagnum = -1 ;
  G__PHG4HoughTransformTPC_DictLN_PHCompositeNode.tagnum = -1 ;
  G__PHG4HoughTransformTPC_DictLN_SubsysReco.tagnum = -1 ;
  G__PHG4HoughTransformTPC_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR.tagnum = -1 ;
  G__PHG4HoughTransformTPC_DictLN_SvtxTrack.tagnum = -1 ;
  G__PHG4HoughTransformTPC_DictLN_SvtxTrackState.tagnum = -1 ;
  G__PHG4HoughTransformTPC_DictLN_PHG4HoughTransformTPC.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablePHG4HoughTransformTPC_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__PHG4HoughTransformTPC_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4HoughTransformTPC_DictLN_string);
   G__get_linked_tagnum_fwd(&G__PHG4HoughTransformTPC_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4HoughTransformTPC_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4HoughTransformTPC_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4HoughTransformTPC_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4HoughTransformTPC_DictLN_Fun4AllBase);
   G__get_linked_tagnum_fwd(&G__PHG4HoughTransformTPC_DictLN_PHCompositeNode);
   G__get_linked_tagnum_fwd(&G__PHG4HoughTransformTPC_DictLN_SubsysReco);
   G__get_linked_tagnum_fwd(&G__PHG4HoughTransformTPC_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4HoughTransformTPC_DictLN_SvtxTrack);
   G__get_linked_tagnum_fwd(&G__PHG4HoughTransformTPC_DictLN_SvtxTrackState);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PHG4HoughTransformTPC_DictLN_PHG4HoughTransformTPC),sizeof(PHG4HoughTransformTPC),-1,197888,(char*)NULL,G__setup_memvarPHG4HoughTransformTPC,G__setup_memfuncPHG4HoughTransformTPC);
}
extern "C" void G__cpp_setupPHG4HoughTransformTPC_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupPHG4HoughTransformTPC_Dict()");
  G__set_cpp_environmentPHG4HoughTransformTPC_Dict();
  G__cpp_setup_tagtablePHG4HoughTransformTPC_Dict();

  G__cpp_setup_inheritancePHG4HoughTransformTPC_Dict();

  G__cpp_setup_typetablePHG4HoughTransformTPC_Dict();

  G__cpp_setup_memvarPHG4HoughTransformTPC_Dict();

  G__cpp_setup_memfuncPHG4HoughTransformTPC_Dict();
  G__cpp_setup_globalPHG4HoughTransformTPC_Dict();
  G__cpp_setup_funcPHG4HoughTransformTPC_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncPHG4HoughTransformTPC_Dict();
  return;
}
class G__cpp_setup_initPHG4HoughTransformTPC_Dict {
  public:
    G__cpp_setup_initPHG4HoughTransformTPC_Dict() { G__add_setup_func("PHG4HoughTransformTPC_Dict",(G__incsetup)(&G__cpp_setupPHG4HoughTransformTPC_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initPHG4HoughTransformTPC_Dict() { G__remove_setup_func("PHG4HoughTransformTPC_Dict"); }
};
G__cpp_setup_initPHG4HoughTransformTPC_Dict G__cpp_setup_initializerPHG4HoughTransformTPC_Dict;

