/********************************************************************
* PHG4SvtxBeamSpotReco_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PHG4SvtxBeamSpotReco_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePHG4SvtxBeamSpotReco_Dict();
extern void G__cpp_setup_inheritancePHG4SvtxBeamSpotReco_Dict();
extern void G__cpp_setup_typetablePHG4SvtxBeamSpotReco_Dict();
extern void G__cpp_setup_memvarPHG4SvtxBeamSpotReco_Dict();
extern void G__cpp_setup_globalPHG4SvtxBeamSpotReco_Dict();
extern void G__cpp_setup_memfuncPHG4SvtxBeamSpotReco_Dict();
extern void G__cpp_setup_funcPHG4SvtxBeamSpotReco_Dict();
extern void G__set_cpp_environmentPHG4SvtxBeamSpotReco_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PHG4SvtxBeamSpotReco.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_string;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_Fun4AllBase;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_PHCompositeNode;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_SubsysReco;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_PHTimeServer;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_PHTimeServercLcLtimer;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_maplEstringcOPHTimeServercLcLtimercOlesslEstringgRcOallocatorlEpairlEconstsPstringcOPHTimeServercLcLtimergRsPgRsPgR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_TPrincipal;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_SvtxBeamSpot;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_SvtxVertexMap;
extern G__linked_taginfo G__PHG4SvtxBeamSpotReco_DictLN_PHG4SvtxBeamSpotReco;

/* STUB derived class for protected member access */
