//
// File generated by rootcint at Tue Mar 28 22:41:49 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME PHG4TrackFastSim_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "PHG4TrackFastSim_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void PHG4TrackFastSim_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void PHG4TrackFastSim_Dictionary();
   static void *new_PHG4TrackFastSim(void *p = 0);
   static void *newArray_PHG4TrackFastSim(Long_t size, void *p);
   static void delete_PHG4TrackFastSim(void *p);
   static void deleteArray_PHG4TrackFastSim(void *p);
   static void destruct_PHG4TrackFastSim(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::PHG4TrackFastSim*)
   {
      ::PHG4TrackFastSim *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::PHG4TrackFastSim),0);
      static ::ROOT::TGenericClassInfo 
         instance("PHG4TrackFastSim", "./PHG4TrackFastSim.h", 49,
                  typeid(::PHG4TrackFastSim), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &PHG4TrackFastSim_Dictionary, isa_proxy, 3,
                  sizeof(::PHG4TrackFastSim) );
      instance.SetNew(&new_PHG4TrackFastSim);
      instance.SetNewArray(&newArray_PHG4TrackFastSim);
      instance.SetDelete(&delete_PHG4TrackFastSim);
      instance.SetDeleteArray(&deleteArray_PHG4TrackFastSim);
      instance.SetDestructor(&destruct_PHG4TrackFastSim);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::PHG4TrackFastSim*)
   {
      return GenerateInitInstanceLocal((::PHG4TrackFastSim*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::PHG4TrackFastSim*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void PHG4TrackFastSim_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::PHG4TrackFastSim*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_PHG4TrackFastSim(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PHG4TrackFastSim : new ::PHG4TrackFastSim;
   }
   static void *newArray_PHG4TrackFastSim(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::PHG4TrackFastSim[nElements] : new ::PHG4TrackFastSim[nElements];
   }
   // Wrapper around operator delete
   static void delete_PHG4TrackFastSim(void *p) {
      delete ((::PHG4TrackFastSim*)p);
   }
   static void deleteArray_PHG4TrackFastSim(void *p) {
      delete [] ((::PHG4TrackFastSim*)p);
   }
   static void destruct_PHG4TrackFastSim(void *p) {
      typedef ::PHG4TrackFastSim current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::PHG4TrackFastSim

/********************************************************
* PHG4TrackFastSim_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablePHG4TrackFastSim_Dict();

extern "C" void G__set_cpp_environmentPHG4TrackFastSim_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("PHG4TrackFastSim.h");
  G__cpp_reset_tagtablePHG4TrackFastSim_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevPHG4TrackFastSim_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* PHG4TrackFastSim */
static int G__PHG4TrackFastSim_Dict_626_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PHG4TrackFastSim* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new PHG4TrackFastSim(*(string*) libp->para[0].ref);
     } else {
       p = new((void*) gvp) PHG4TrackFastSim(*(string*) libp->para[0].ref);
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new PHG4TrackFastSim[n];
       } else {
         p = new((void*) gvp) PHG4TrackFastSim[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new PHG4TrackFastSim;
       } else {
         p = new((void*) gvp) PHG4TrackFastSim;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSim));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->Verbosity((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const PHG4TrackFastSim*) G__getstructoffset())->is_do_evt_display());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_do_evt_display((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PHG4TrackFastSim*) G__getstructoffset())->get_phi_resolution());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_phi_resolution((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PHG4TrackFastSim*) G__getstructoffset())->get_r_resolution());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_r_resolution((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string& obj = ((const PHG4TrackFastSim*) G__getstructoffset())->get_fit_alg_name();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_fit_alg_name(*(string*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string& obj = ((const PHG4TrackFastSim*) G__getstructoffset())->get_mag_field_file_name();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_mag_field_file_name(*(string*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const PHG4TrackFastSim*) G__getstructoffset())->get_mag_field_re_scaling_factor());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_mag_field_re_scaling_factor((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const PHG4TrackFastSim*) G__getstructoffset())->is_reverse_mag_field());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_reverse_mag_field((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PHG4TrackFastSim*) G__getstructoffset())->get_pat_rec_hit_finding_eff());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_pat_rec_hit_finding_eff((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PHG4TrackFastSim*) G__getstructoffset())->get_pat_rec_noise_prob());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_pat_rec_noise_prob((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const vector<std::string>& obj = ((const PHG4TrackFastSim*) G__getstructoffset())->get_phg4hits_names();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_phg4hits_names(*(vector<std::string>*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_phg4hits_names((string*) G__int(libp->para[0]), (const int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_state_names((string*) G__int(libp->para[0]), (const int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PHG4TrackFastSim*) G__getstructoffset())->get_z_resolution());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_z_resolution((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const PHG4TrackFastSim*) G__getstructoffset())->get_detector_type());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_detector_type((PHG4TrackFastSim::DETECTOR_TYPE) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string& obj = ((const PHG4TrackFastSim*) G__getstructoffset())->get_trackmap_out_name();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_trackmap_out_name(*(string*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const string& obj = ((const PHG4TrackFastSim*) G__getstructoffset())->get_sub_top_node_name();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_sub_top_node_name(*(string*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const PHG4TrackFastSim*) G__getstructoffset())->is_use_vertex_in_fitting());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_use_vertex_in_fitting((bool) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PHG4TrackFastSim*) G__getstructoffset())->get_vertex_xy_resolution());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_vertex_xy_resolution((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const PHG4TrackFastSim*) G__getstructoffset())->get_vertex_z_resolution());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_vertex_z_resolution((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((const PHG4TrackFastSim*) G__getstructoffset())->get_primary_assumption_pid());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_primary_assumption_pid((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__PHG4TrackFastSim_Dict_626_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((PHG4TrackFastSim*) G__getstructoffset())->set_primary_tracking((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__PHG4TrackFastSim_Dict_626_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   PHG4TrackFastSim* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new PHG4TrackFastSim(*(PHG4TrackFastSim*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSim));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef PHG4TrackFastSim G__TPHG4TrackFastSim;
static int G__PHG4TrackFastSim_Dict_626_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (PHG4TrackFastSim*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((PHG4TrackFastSim*) (soff+(sizeof(PHG4TrackFastSim)*i)))->~G__TPHG4TrackFastSim();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (PHG4TrackFastSim*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((PHG4TrackFastSim*) (soff))->~G__TPHG4TrackFastSim();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__PHG4TrackFastSim_Dict_626_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   PHG4TrackFastSim* dest = (PHG4TrackFastSim*) G__getstructoffset();
   *dest = *(PHG4TrackFastSim*) libp->para[0].ref;
   const PHG4TrackFastSim& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* PHG4TrackFastSim */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncPHG4TrackFastSim_Dict {
 public:
  G__Sizep2memfuncPHG4TrackFastSim_Dict(): p(&G__Sizep2memfuncPHG4TrackFastSim_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncPHG4TrackFastSim_Dict::*p)();
};

size_t G__get_sizep2memfuncPHG4TrackFastSim_Dict()
{
  G__Sizep2memfuncPHG4TrackFastSim_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancePHG4TrackFastSim_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSim))) {
     PHG4TrackFastSim *G__Lderived;
     G__Lderived=(PHG4TrackFastSim*)0x1000;
     {
       SubsysReco *G__Lpbase=(SubsysReco*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSim),G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_SubsysReco),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       Fun4AllBase *G__Lpbase=(Fun4AllBase*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSim),G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_Fun4AllBase),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablePHG4TrackFastSim_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<PHG4HitDefs::keytype,PHG4Hit*>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_maplEunsignedsPlongsPlongcOPHG4HitmUcOlesslEunsignedsPlongsPlonggRcOallocatorlEpairlEconstsPunsignedsPlongsPlongcOPHG4HitmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned long long,PHG4Hit*>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_maplEunsignedsPlongsPlongcOPHG4HitmUcOlesslEunsignedsPlongsPlonggRcOallocatorlEpairlEconstsPunsignedsPlongsPlongcOPHG4HitmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned long long,PHG4Hit*,less<unsigned long long> >",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_maplEunsignedsPlongsPlongcOPHG4HitmUcOlesslEunsignedsPlongsPlonggRcOallocatorlEpairlEconstsPunsignedsPlongsPlongcOPHG4HitmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<unsigned int>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<unsigned int,less<unsigned int> >",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<genfit::MatStep>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEgenfitcLcLMatStepcOallocatorlEgenfitcLcLMatStepgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEgenfitcLcLMatStepcOallocatorlEgenfitcLcLMatStepgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEgenfitcLcLMatStepcOallocatorlEgenfitcLcLMatStepgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEgenfitcLcLMatStepcOallocatorlEgenfitcLcLMatStepgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEgenfitcLcLMatStepcOallocatorlEgenfitcLcLMatStepgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<genfit::MeasurementOnPlane*>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEgenfitcLcLMeasurementOnPlanemUcOallocatorlEgenfitcLcLMeasurementOnPlanemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEgenfitcLcLMeasurementOnPlanemUcOallocatorlEgenfitcLcLMeasurementOnPlanemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEgenfitcLcLMeasurementOnPlanemUcOallocatorlEgenfitcLcLMeasurementOnPlanemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEgenfitcLcLMeasurementOnPlanemUcOallocatorlEgenfitcLcLMeasurementOnPlanemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEgenfitcLcLMeasurementOnPlanemUcOallocatorlEgenfitcLcLMeasurementOnPlanemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<PHGenFit::Measurement*>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEPHGenFitcLcLMeasurementmUcOallocatorlEPHGenFitcLcLMeasurementmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEPHGenFitcLcLMeasurementmUcOallocatorlEPHGenFitcLcLMeasurementmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEPHGenFitcLcLMeasurementmUcOallocatorlEPHGenFitcLcLMeasurementmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEPHGenFitcLcLMeasurementmUcOallocatorlEPHGenFitcLcLMeasurementmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEPHGenFitcLcLMeasurementmUcOallocatorlEPHGenFitcLcLMeasurementmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<PHG4HitContainer*>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEPHG4HitContainermUcOallocatorlEPHG4HitContainermUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEPHG4HitContainermUcOallocatorlEPHG4HitContainermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEPHG4HitContainermUcOallocatorlEPHG4HitContainermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEPHG4HitContainermUcOallocatorlEPHG4HitContainermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEPHG4HitContainermUcOallocatorlEPHG4HitContainermUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* PHG4TrackFastSim */
static void G__setup_memvarPHG4TrackFastSim(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSim));
   { PHG4TrackFastSim *p; p=(PHG4TrackFastSim*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSimcLcLDETECTOR_TYPE),-1,-2,1,G__FastAllocString(2048).Format("Vertical_Plane=%lldLL",(long long)PHG4TrackFastSim::Vertical_Plane).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSimcLcLDETECTOR_TYPE),-1,-2,1,G__FastAllocString(2048).Format("Cylinder=%lldLL",(long long)PHG4TrackFastSim::Cylinder).data(),0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_event=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSimcLcLDETECTOR_TYPE),-1,-1,4,"_detector_type=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TruthInfoContainer),-1,-1,4,"_truth_container=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEPHG4HitContainermUcOallocatorlEPHG4HitContainermUgRsPgR),G__defined_typename("vector<PHG4HitContainer*>"),-1,4,"_phg4hits=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,4,"_phg4hits_names=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_string),-1,-1,4,"_sub_top_node_name=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_string),-1,-1,4,"_trackmap_out_name=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_SvtxTrackMap),-1,-1,4,"_trackmap_out=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHGenFitcLcLFitter),-1,-1,4,"_fitter=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_string),-1,-1,4,"_mag_field_file_name=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"_mag_field_re_scaling_factor=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_reverse_mag_field=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_string),-1,-1,4,"_fit_alg_name=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_primary_assumption_pid=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_do_evt_display=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"_use_vertex_in_fitting=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_vertex_xy_resolution=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_vertex_z_resolution=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_phi_resolution=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_r_resolution=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_z_resolution=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_pat_rec_hit_finding_eff=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"_pat_rec_noise_prob=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_N_DETECTOR_LAYER=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_primary_tracking=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_N_STATES=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,4,"_state_names=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"_state_location=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarPHG4TrackFastSim_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncPHG4TrackFastSim(void) {
   /* PHG4TrackFastSim */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSim));
   G__memfunc_setup("PHG4TrackFastSim",1471,G__PHG4TrackFastSim_Dict_626_0_1, 105, G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSim), -1, 0, 1, 1, 1, 0, "u 'string' - 11 '\"PHG4TrackFastSim\"' name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("InitRun",713,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("process_event",1408,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("End",279,(G__InterfaceMethod) NULL,105, -1, -1, 0, 1, 1, 1, 0, "U 'PHCompositeNode' - 0 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Verbosity",967,G__PHG4TrackFastSim_Dict_626_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - verb", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("is_do_evt_display",1809,G__PHG4TrackFastSim_Dict_626_0_7, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_do_evt_display",1921,G__PHG4TrackFastSim_Dict_626_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - doEvtDisplay", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_phi_resolution",1939,G__PHG4TrackFastSim_Dict_626_0_9, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_phi_resolution",1951,G__PHG4TrackFastSim_Dict_626_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - fgemPhiResolution", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_r_resolution",1732,G__PHG4TrackFastSim_Dict_626_0_11, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_r_resolution",1744,G__PHG4TrackFastSim_Dict_626_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - fgemRResolution", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_fit_alg_name",1653,G__PHG4TrackFastSim_Dict_626_0_13, 117, G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_string), -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_fit_alg_name",1665,G__PHG4TrackFastSim_Dict_626_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 11 - fitAlgName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_mag_field_file_name",2358,G__PHG4TrackFastSim_Dict_626_0_15, 117, G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_string), -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_mag_field_file_name",2370,G__PHG4TrackFastSim_Dict_626_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 11 - magFieldFileName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_mag_field_re_scaling_factor",3211,G__PHG4TrackFastSim_Dict_626_0_17, 102, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_mag_field_re_scaling_factor",3223,G__PHG4TrackFastSim_Dict_626_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - magFieldReScalingFactor", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("is_reverse_mag_field",2094,G__PHG4TrackFastSim_Dict_626_0_19, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_reverse_mag_field",2206,G__PHG4TrackFastSim_Dict_626_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - reverseMagField", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_pat_rec_hit_finding_eff",2799,G__PHG4TrackFastSim_Dict_626_0_21, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_pat_rec_hit_finding_eff",2811,G__PHG4TrackFastSim_Dict_626_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - patRecHitFindingEff", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_pat_rec_noise_prob",2316,G__PHG4TrackFastSim_Dict_626_0_23, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_pat_rec_noise_prob",2328,G__PHG4TrackFastSim_Dict_626_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - patRecNoiseProb", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_phg4hits_names",1853,G__PHG4TrackFastSim_Dict_626_0_25, 117, G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_vectorlEstringcOallocatorlEstringgRsPgR), G__defined_typename("vector<std::string>"), 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_phg4hits_names",1865,G__PHG4TrackFastSim_Dict_626_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "u 'vector<string,allocator<string> >' 'vector<std::string>' 11 - phg4hitsNames", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_phg4hits_names",1865,G__PHG4TrackFastSim_Dict_626_0_27, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'string' - 10 - phg4hitsNames i - - 10 - nlayer", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_state_names",1599,G__PHG4TrackFastSim_Dict_626_0_28, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'string' - 10 - stateNames i - - 10 - nlayer", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_z_resolution",1740,G__PHG4TrackFastSim_Dict_626_0_29, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_z_resolution",1752,G__PHG4TrackFastSim_Dict_626_0_30, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - resolution", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_detector_type",1818,G__PHG4TrackFastSim_Dict_626_0_31, 105, G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSimcLcLDETECTOR_TYPE), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_detector_type",1830,G__PHG4TrackFastSim_Dict_626_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "i 'PHG4TrackFastSim::DETECTOR_TYPE' - 0 - detectorType", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_trackmap_out_name",2217,G__PHG4TrackFastSim_Dict_626_0_33, 117, G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_string), -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_trackmap_out_name",2229,G__PHG4TrackFastSim_Dict_626_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 11 - trackmapOutName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_sub_top_node_name",2208,G__PHG4TrackFastSim_Dict_626_0_35, 117, G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_string), -1, 1, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_sub_top_node_name",2220,G__PHG4TrackFastSim_Dict_626_0_36, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 11 - subTopNodeName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("is_use_vertex_in_fitting",2575,G__PHG4TrackFastSim_Dict_626_0_37, 103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_use_vertex_in_fitting",2687,G__PHG4TrackFastSim_Dict_626_0_38, 121, -1, -1, 0, 1, 1, 1, 0, "g - - 0 - useVertexInFitting", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_vertex_xy_resolution",2624,G__PHG4TrackFastSim_Dict_626_0_39, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_vertex_xy_resolution",2636,G__PHG4TrackFastSim_Dict_626_0_40, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - vertexXyResolution", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_vertex_z_resolution",2505,G__PHG4TrackFastSim_Dict_626_0_41, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_vertex_z_resolution",2517,G__PHG4TrackFastSim_Dict_626_0_42, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - vertexZResolution", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_primary_assumption_pid",2801,G__PHG4TrackFastSim_Dict_626_0_43, 105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_primary_assumption_pid",2813,G__PHG4TrackFastSim_Dict_626_0_44, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - primaryAssumptionPid", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("set_primary_tracking",2145,G__PHG4TrackFastSim_Dict_626_0_45, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - pTrk", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CreateNodes",1101,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 1, 1, 4, 0, "U 'PHCompositeNode' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNodes",793,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 1, 1, 4, 0, "U 'PHCompositeNode' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PseudoPatternRecognition",2511,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 6, 1, 4, 0, 
"U 'PHG4Particle' - 10 - particle u 'vector<PHGenFit::Measurement*,allocator<PHGenFit::Measurement*> >' 'vector<PHGenFit::Measurement*>' 1 - meas_out "
"u 'TVector3' - 1 - seed_pos u 'TVector3' - 1 - seed_mom "
"u 'TMatrixTSym<double>' 'TMatrixDSym' 1 - seed_cov g - - 10 'true' do_smearing", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PHG4HitToMeasurementVerticalPlane",3243,(G__InterfaceMethod) NULL, 85, G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHGenFitcLcLPlanarMeasurement), -1, 0, 3, 1, 4, 0, 
"U 'PHG4Hit' - 10 - g4hit d - - 10 - phi_resolution "
"d - - 10 - r_resolution", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PHG4HitToMeasurementCylinder",2747,(G__InterfaceMethod) NULL, 85, G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHGenFitcLcLPlanarMeasurement), -1, 0, 3, 1, 4, 0, 
"U 'PHG4Hit' - 10 - g4hit d - - 10 - phi_resolution "
"d - - 10 - z_resolution", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("VertexMeasurement",1796,(G__InterfaceMethod) NULL, 85, G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHGenFitcLcLMeasurement), -1, 0, 3, 1, 4, 0, 
"u 'TVector3' - 11 - vtx d - - 0 - dxy "
"d - - 0 - dz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MakeSvtxTrack",1320,(G__InterfaceMethod) NULL, 85, G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_SvtxTrack), -1, 0, 4, 1, 4, 0, 
"U 'PHGenFit::Track' - 10 - phgf_track_in h - - 10 'UINT_MAX' truth_track_id "
"h - - 10 '0' nmeas u 'TVector3' - 11 'TVector3(0.0,0.0,0.0)' vtx", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("PHG4TrackFastSim", 1471, G__PHG4TrackFastSim_Dict_626_0_53, (int) ('i'), G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSim), -1, 0, 1, 1, 1, 0, "u 'PHG4TrackFastSim' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~PHG4TrackFastSim", 1597, G__PHG4TrackFastSim_Dict_626_0_54, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__PHG4TrackFastSim_Dict_626_0_55, (int) ('u'), G__get_linked_tagnum(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSim), -1, 1, 1, 1, 1, 0, "u 'PHG4TrackFastSim' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncPHG4TrackFastSim_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalPHG4TrackFastSim_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcPHG4TrackFastSim_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__PHG4TrackFastSim_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_Fun4AllBase = { "Fun4AllBase" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_PHCompositeNode = { "PHCompositeNode" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_SubsysReco = { "SubsysReco" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_PHG4Hit = { "PHG4Hit" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_maplEunsignedsPlongsPlongcOPHG4HitmUcOlesslEunsignedsPlongsPlonggRcOallocatorlEpairlEconstsPunsignedsPlongsPlongcOPHG4HitmUgRsPgRsPgR = { "map<unsigned long long,PHG4Hit*,less<unsigned long long>,allocator<pair<const unsigned long long,PHG4Hit*> > >" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR = { "set<unsigned int,less<unsigned int>,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_vectorlEgenfitcLcLMatStepcOallocatorlEgenfitcLcLMatStepgRsPgR = { "vector<genfit::MatStep,allocator<genfit::MatStep> >" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEgenfitcLcLMatStepcOallocatorlEgenfitcLcLMatStepgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<genfit::MatStep,allocator<genfit::MatStep> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_vectorlEgenfitcLcLMeasurementOnPlanemUcOallocatorlEgenfitcLcLMeasurementOnPlanemUgRsPgR = { "vector<genfit::MeasurementOnPlane*,allocator<genfit::MeasurementOnPlane*> >" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEgenfitcLcLMeasurementOnPlanemUcOallocatorlEgenfitcLcLMeasurementOnPlanemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<genfit::MeasurementOnPlane*,allocator<genfit::MeasurementOnPlane*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_PHGenFit = { "PHGenFit" , 110 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_PHGenFitcLcLMeasurement = { "PHGenFit::Measurement" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_PHG4Particle = { "PHG4Particle" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_PHGenFitcLcLPlanarMeasurement = { "PHGenFit::PlanarMeasurement" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_PHGenFitcLcLTrack = { "PHGenFit::Track" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_SvtxTrack = { "SvtxTrack" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_PHGenFitcLcLFitter = { "PHGenFit::Fitter" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_SvtxTrackMap = { "SvtxTrackMap" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_PHG4TruthInfoContainer = { "PHG4TruthInfoContainer" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_PHG4TrackFastSim = { "PHG4TrackFastSim" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_PHG4TrackFastSimcLcLDETECTOR_TYPE = { "PHG4TrackFastSim::DETECTOR_TYPE" , 101 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_vectorlEPHGenFitcLcLMeasurementmUcOallocatorlEPHGenFitcLcLMeasurementmUgRsPgR = { "vector<PHGenFit::Measurement*,allocator<PHGenFit::Measurement*> >" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEPHGenFitcLcLMeasurementmUcOallocatorlEPHGenFitcLcLMeasurementmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<PHGenFit::Measurement*,allocator<PHGenFit::Measurement*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_vectorlEPHG4HitContainermUcOallocatorlEPHG4HitContainermUgRsPgR = { "vector<PHG4HitContainer*,allocator<PHG4HitContainer*> >" , 99 , -1 };
G__linked_taginfo G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEPHG4HitContainermUcOallocatorlEPHG4HitContainermUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<PHG4HitContainer*,allocator<PHG4HitContainer*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablePHG4TrackFastSim_Dict() {
  G__PHG4TrackFastSim_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_string.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_Fun4AllBase.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_PHCompositeNode.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_SubsysReco.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_PHG4Hit.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_maplEunsignedsPlongsPlongcOPHG4HitmUcOlesslEunsignedsPlongsPlonggRcOallocatorlEpairlEconstsPunsignedsPlongsPlongcOPHG4HitmUgRsPgRsPgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TVector3.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_vectorlEgenfitcLcLMatStepcOallocatorlEgenfitcLcLMatStepgRsPgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEgenfitcLcLMatStepcOallocatorlEgenfitcLcLMatStepgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_vectorlEgenfitcLcLMeasurementOnPlanemUcOallocatorlEgenfitcLcLMeasurementOnPlanemUgRsPgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEgenfitcLcLMeasurementOnPlanemUcOallocatorlEgenfitcLcLMeasurementOnPlanemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_PHGenFit.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_PHGenFitcLcLMeasurement.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_PHG4Particle.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_PHGenFitcLcLPlanarMeasurement.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_PHGenFitcLcLTrack.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_SvtxTrack.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_PHGenFitcLcLFitter.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_SvtxTrackMap.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_PHG4TruthInfoContainer.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_PHG4TrackFastSim.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_PHG4TrackFastSimcLcLDETECTOR_TYPE.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_vectorlEPHGenFitcLcLMeasurementmUcOallocatorlEPHGenFitcLcLMeasurementmUgRsPgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEPHGenFitcLcLMeasurementmUcOallocatorlEPHGenFitcLcLMeasurementmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_vectorlEPHG4HitContainermUcOallocatorlEPHG4HitContainermUgRsPgR.tagnum = -1 ;
  G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEPHG4HitContainermUcOallocatorlEPHG4HitContainermUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablePHG4TrackFastSim_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_string);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_Fun4AllBase);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_PHCompositeNode);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_SubsysReco);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_PHG4Hit);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_maplEunsignedsPlongsPlongcOPHG4HitmUcOlesslEunsignedsPlongsPlonggRcOallocatorlEpairlEconstsPunsignedsPlongsPlongcOPHG4HitmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TVector3);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_vectorlEgenfitcLcLMatStepcOallocatorlEgenfitcLcLMatStepgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEgenfitcLcLMatStepcOallocatorlEgenfitcLcLMatStepgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_vectorlEgenfitcLcLMeasurementOnPlanemUcOallocatorlEgenfitcLcLMeasurementOnPlanemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEgenfitcLcLMeasurementOnPlanemUcOallocatorlEgenfitcLcLMeasurementOnPlanemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_PHGenFit);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_PHGenFitcLcLMeasurement);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_PHG4Particle);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_PHGenFitcLcLPlanarMeasurement);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_PHGenFitcLcLTrack);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_SvtxTrack);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_PHGenFitcLcLFitter);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_SvtxTrackMap);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_PHG4TruthInfoContainer);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSim),sizeof(PHG4TrackFastSim),-1,197888,(char*)NULL,G__setup_memvarPHG4TrackFastSim,G__setup_memfuncPHG4TrackFastSim);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_PHG4TrackFastSimcLcLDETECTOR_TYPE);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_vectorlEPHGenFitcLcLMeasurementmUcOallocatorlEPHGenFitcLcLMeasurementmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEPHGenFitcLcLMeasurementmUcOallocatorlEPHGenFitcLcLMeasurementmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_vectorlEPHG4HitContainermUcOallocatorlEPHG4HitContainermUgRsPgR);
   G__get_linked_tagnum_fwd(&G__PHG4TrackFastSim_DictLN_reverse_iteratorlEvectorlEPHG4HitContainermUcOallocatorlEPHG4HitContainermUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupPHG4TrackFastSim_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupPHG4TrackFastSim_Dict()");
  G__set_cpp_environmentPHG4TrackFastSim_Dict();
  G__cpp_setup_tagtablePHG4TrackFastSim_Dict();

  G__cpp_setup_inheritancePHG4TrackFastSim_Dict();

  G__cpp_setup_typetablePHG4TrackFastSim_Dict();

  G__cpp_setup_memvarPHG4TrackFastSim_Dict();

  G__cpp_setup_memfuncPHG4TrackFastSim_Dict();
  G__cpp_setup_globalPHG4TrackFastSim_Dict();
  G__cpp_setup_funcPHG4TrackFastSim_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncPHG4TrackFastSim_Dict();
  return;
}
class G__cpp_setup_initPHG4TrackFastSim_Dict {
  public:
    G__cpp_setup_initPHG4TrackFastSim_Dict() { G__add_setup_func("PHG4TrackFastSim_Dict",(G__incsetup)(&G__cpp_setupPHG4TrackFastSim_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initPHG4TrackFastSim_Dict() { G__remove_setup_func("PHG4TrackFastSim_Dict"); }
};
G__cpp_setup_initPHG4TrackFastSim_Dict G__cpp_setup_initializerPHG4TrackFastSim_Dict;

