//
// File generated by rootcint at Tue Mar 28 22:26:27 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME SvtxHitMap_v1_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "SvtxHitMap_v1_Dict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void SvtxHitMap_v1_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_SvtxHitMap_v1(void *p = 0);
   static void *newArray_SvtxHitMap_v1(Long_t size, void *p);
   static void delete_SvtxHitMap_v1(void *p);
   static void deleteArray_SvtxHitMap_v1(void *p);
   static void destruct_SvtxHitMap_v1(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::SvtxHitMap_v1*)
   {
      ::SvtxHitMap_v1 *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::SvtxHitMap_v1 >(0);
      static ::ROOT::TGenericClassInfo 
         instance("SvtxHitMap_v1", ::SvtxHitMap_v1::Class_Version(), "./SvtxHitMap_v1.h", 11,
                  typeid(::SvtxHitMap_v1), ::ROOT::DefineBehavior(ptr, ptr),
                  &::SvtxHitMap_v1::Dictionary, isa_proxy, 4,
                  sizeof(::SvtxHitMap_v1) );
      instance.SetNew(&new_SvtxHitMap_v1);
      instance.SetNewArray(&newArray_SvtxHitMap_v1);
      instance.SetDelete(&delete_SvtxHitMap_v1);
      instance.SetDeleteArray(&deleteArray_SvtxHitMap_v1);
      instance.SetDestructor(&destruct_SvtxHitMap_v1);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::SvtxHitMap_v1*)
   {
      return GenerateInitInstanceLocal((::SvtxHitMap_v1*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SvtxHitMap_v1*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr SvtxHitMap_v1::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *SvtxHitMap_v1::Class_Name()
{
   return "SvtxHitMap_v1";
}

//______________________________________________________________________________
const char *SvtxHitMap_v1::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SvtxHitMap_v1*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int SvtxHitMap_v1::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SvtxHitMap_v1*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void SvtxHitMap_v1::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SvtxHitMap_v1*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *SvtxHitMap_v1::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SvtxHitMap_v1*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void SvtxHitMap_v1::Streamer(TBuffer &R__b)
{
   // Stream an object of class SvtxHitMap_v1.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(SvtxHitMap_v1::Class(),this);
   } else {
      R__b.WriteClassBuffer(SvtxHitMap_v1::Class(),this);
   }
}

//______________________________________________________________________________
void SvtxHitMap_v1::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class SvtxHitMap_v1.
      TClass *R__cl = ::SvtxHitMap_v1::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_map", (void*)&_map);
      R__insp.InspectMember("SvtxHitMap::HitMap", (void*)&_map, "_map.", false);
      SvtxHitMap::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_SvtxHitMap_v1(void *p) {
      return  p ? new(p) ::SvtxHitMap_v1 : new ::SvtxHitMap_v1;
   }
   static void *newArray_SvtxHitMap_v1(Long_t nElements, void *p) {
      return p ? new(p) ::SvtxHitMap_v1[nElements] : new ::SvtxHitMap_v1[nElements];
   }
   // Wrapper around operator delete
   static void delete_SvtxHitMap_v1(void *p) {
      delete ((::SvtxHitMap_v1*)p);
   }
   static void deleteArray_SvtxHitMap_v1(void *p) {
      delete [] ((::SvtxHitMap_v1*)p);
   }
   static void destruct_SvtxHitMap_v1(void *p) {
      typedef ::SvtxHitMap_v1 current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::SvtxHitMap_v1

namespace ROOTDict {
   void maplEunsignedsPintcOSvtxHitmUgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEunsignedsPintcOSvtxHitmUgR_Dictionary();
   static void *new_maplEunsignedsPintcOSvtxHitmUgR(void *p = 0);
   static void *newArray_maplEunsignedsPintcOSvtxHitmUgR(Long_t size, void *p);
   static void delete_maplEunsignedsPintcOSvtxHitmUgR(void *p);
   static void deleteArray_maplEunsignedsPintcOSvtxHitmUgR(void *p);
   static void destruct_maplEunsignedsPintcOSvtxHitmUgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const map<unsigned int,SvtxHit*>*)
   {
      map<unsigned int,SvtxHit*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<unsigned int,SvtxHit*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<unsigned int,SvtxHit*>", -2, "prec_stl/map", 63,
                  typeid(map<unsigned int,SvtxHit*>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &maplEunsignedsPintcOSvtxHitmUgR_Dictionary, isa_proxy, 0,
                  sizeof(map<unsigned int,SvtxHit*>) );
      instance.SetNew(&new_maplEunsignedsPintcOSvtxHitmUgR);
      instance.SetNewArray(&newArray_maplEunsignedsPintcOSvtxHitmUgR);
      instance.SetDelete(&delete_maplEunsignedsPintcOSvtxHitmUgR);
      instance.SetDeleteArray(&deleteArray_maplEunsignedsPintcOSvtxHitmUgR);
      instance.SetDestructor(&destruct_maplEunsignedsPintcOSvtxHitmUgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::MapInsert< map<unsigned int,SvtxHit*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<unsigned int,SvtxHit*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEunsignedsPintcOSvtxHitmUgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const map<unsigned int,SvtxHit*>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_maplEunsignedsPintcOSvtxHitmUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<unsigned int,SvtxHit*> : new map<unsigned int,SvtxHit*>;
   }
   static void *newArray_maplEunsignedsPintcOSvtxHitmUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<unsigned int,SvtxHit*>[nElements] : new map<unsigned int,SvtxHit*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEunsignedsPintcOSvtxHitmUgR(void *p) {
      delete ((map<unsigned int,SvtxHit*>*)p);
   }
   static void deleteArray_maplEunsignedsPintcOSvtxHitmUgR(void *p) {
      delete [] ((map<unsigned int,SvtxHit*>*)p);
   }
   static void destruct_maplEunsignedsPintcOSvtxHitmUgR(void *p) {
      typedef map<unsigned int,SvtxHit*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class map<unsigned int,SvtxHit*>

/********************************************************
* SvtxHitMap_v1_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableSvtxHitMap_v1_Dict();

extern "C" void G__set_cpp_environmentSvtxHitMap_v1_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("SvtxHitMap_v1.h");
  G__cpp_reset_tagtableSvtxHitMap_v1_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevSvtxHitMap_v1_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SvtxHitMap_v1 */
static int G__SvtxHitMap_v1_Dict_423_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SvtxHitMap_v1* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SvtxHitMap_v1[n];
     } else {
       p = new((void*) gvp) SvtxHitMap_v1[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SvtxHitMap_v1;
     } else {
       p = new((void*) gvp) SvtxHitMap_v1;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHitMap_v1_Dict_423_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SvtxHitMap_v1* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new SvtxHitMap_v1(*(SvtxHitMap_v1*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) SvtxHitMap_v1(*(SvtxHitMap_v1*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHitMap_v1_Dict_423_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const SvtxHitMap_v1& obj = ((SvtxHitMap_v1*) G__getstructoffset())->operator=(*(SvtxHitMap_v1*) libp->para[0].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHitMap_v1_Dict_423_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) SvtxHitMap_v1::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHitMap_v1_Dict_423_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SvtxHitMap_v1::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHitMap_v1_Dict_423_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) SvtxHitMap_v1::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHitMap_v1_Dict_423_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SvtxHitMap_v1::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHitMap_v1_Dict_423_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxHitMap_v1*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHitMap_v1_Dict_423_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SvtxHitMap_v1::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHitMap_v1_Dict_423_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SvtxHitMap_v1::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHitMap_v1_Dict_423_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SvtxHitMap_v1::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHitMap_v1_Dict_423_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SvtxHitMap_v1::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SvtxHitMap_v1 G__TSvtxHitMap_v1;
static int G__SvtxHitMap_v1_Dict_423_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SvtxHitMap_v1*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SvtxHitMap_v1*) (soff+(sizeof(SvtxHitMap_v1)*i)))->~G__TSvtxHitMap_v1();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SvtxHitMap_v1*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SvtxHitMap_v1*) (soff))->~G__TSvtxHitMap_v1();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SvtxHitMap_v1 */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncSvtxHitMap_v1_Dict {
 public:
  G__Sizep2memfuncSvtxHitMap_v1_Dict(): p(&G__Sizep2memfuncSvtxHitMap_v1_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncSvtxHitMap_v1_Dict::*p)();
};

size_t G__get_sizep2memfuncSvtxHitMap_v1_Dict()
{
  G__Sizep2memfuncSvtxHitMap_v1_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceSvtxHitMap_v1_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1))) {
     SvtxHitMap_v1 *G__Lderived;
     G__Lderived=(SvtxHitMap_v1*)0x1000;
     {
       SvtxHitMap *G__Lpbase=(SvtxHitMap*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1),G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHitMap),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       PHObject *G__Lpbase=(PHObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1),G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_PHObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1),G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableSvtxHitMap_v1_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned int,SvtxHit*>",117,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<unsigned int,SvtxHit*,less<unsigned int> >",117,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SvtxHitMap_v1 */
static void G__setup_memvarSvtxHitMap_v1(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1));
   { SvtxHitMap_v1 *p; p=(SvtxHitMap_v1*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgR),G__defined_typename("HitMap"),-1,4,"_map=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarSvtxHitMap_v1_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSvtxHitMap_v1(void) {
   /* SvtxHitMap_v1 */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1));
   G__memfunc_setup("SvtxHitMap_v1",1278,G__SvtxHitMap_v1_Dict_423_0_1, 105, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SvtxHitMap_v1",1278,G__SvtxHitMap_v1_Dict_423_0_2, 105, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1), -1, 0, 1, 1, 1, 0, "u 'SvtxHitMap_v1' - 11 - hitmap", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,G__SvtxHitMap_v1_Dict_423_0_3, 117, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1), -1, 1, 1, 1, 1, 0, "u 'SvtxHitMap_v1' - 11 - hitmap", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("identify",860,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 8, "u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 'std::cout' os", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Reset",515,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("isValid",716,(G__InterfaceMethod) NULL,105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Clone",497,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHitMap), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("empty",559,(G__InterfaceMethod) NULL,103, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("size",443,(G__InterfaceMethod) NULL,107, -1, G__defined_typename("size_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("count",553,(G__InterfaceMethod) NULL,107, -1, G__defined_typename("size_t"), 0, 1, 1, 1, 8, "h - - 0 - idkey", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("clear",519,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get",320,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHit), -1, 0, 1, 1, 1, 9, "h - - 0 - idkey", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get",320,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHit), -1, 0, 1, 1, 1, 0, "h - - 0 - idkey", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("insert",661,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_SvtxHit), -1, 0, 1, 1, 1, 0, "U 'SvtxHit' - 10 - hit", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("erase",528,(G__InterfaceMethod) NULL,107, -1, G__defined_typename("size_t"), 0, 1, 1, 1, 0, "h - - 0 - idkey", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("begin",517,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgRcLcLiterator), G__defined_typename("SvtxHitMap::ConstIter"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("find",417,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgRcLcLiterator), G__defined_typename("SvtxHitMap::ConstIter"), 0, 1, 1, 1, 8, "h - - 0 - idkey", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("end",311,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgRcLcLiterator), G__defined_typename("SvtxHitMap::ConstIter"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("begin",517,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgRcLcLiterator), G__defined_typename("SvtxHitMap::Iter"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("find",417,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgRcLcLiterator), G__defined_typename("SvtxHitMap::Iter"), 0, 1, 1, 1, 0, "h - - 0 - idkey", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("end",311,(G__InterfaceMethod) NULL,117, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgRcLcLiterator), G__defined_typename("SvtxHitMap::Iter"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__SvtxHitMap_v1_Dict_423_0_22, 85, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&SvtxHitMap_v1::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__SvtxHitMap_v1_Dict_423_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SvtxHitMap_v1::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__SvtxHitMap_v1_Dict_423_0_24, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&SvtxHitMap_v1::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__SvtxHitMap_v1_Dict_423_0_25, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&SvtxHitMap_v1::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__SvtxHitMap_v1_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__SvtxHitMap_v1_Dict_423_0_29, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__SvtxHitMap_v1_Dict_423_0_30, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SvtxHitMap_v1::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__SvtxHitMap_v1_Dict_423_0_31, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SvtxHitMap_v1::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__SvtxHitMap_v1_Dict_423_0_32, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SvtxHitMap_v1::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__SvtxHitMap_v1_Dict_423_0_33, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SvtxHitMap_v1::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~SvtxHitMap_v1", 1404, G__SvtxHitMap_v1_Dict_423_0_34, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncSvtxHitMap_v1_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalSvtxHitMap_v1_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcSvtxHitMap_v1_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__SvtxHitMap_v1_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR = { "basic_ostream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_PHObject = { "PHObject" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_SvtxHit = { "SvtxHit" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_SvtxHitMap = { "SvtxHitMap" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgR = { "map<unsigned int,SvtxHit*,less<unsigned int>,allocator<pair<const unsigned int,SvtxHit*> > >" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgRcLcLiterator = { "map<unsigned int,SvtxHit*,less<unsigned int>,allocator<pair<const unsigned int,SvtxHit*> > >::iterator" , 99 , -1 };
G__linked_taginfo G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1 = { "SvtxHitMap_v1" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableSvtxHitMap_v1_Dict() {
  G__SvtxHitMap_v1_DictLN_TClass.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_TBuffer.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_TMemberInspector.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_TObject.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_PHObject.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_SvtxHit.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_SvtxHitMap.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgR.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgRcLcLiterator.tagnum = -1 ;
  G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableSvtxHitMap_v1_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_PHObject);
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_SvtxHit);
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_SvtxHitMap);
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_maplEunsignedsPintcOSvtxHitmUcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOSvtxHitmUgRsPgRsPgRcLcLiterator);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SvtxHitMap_v1_DictLN_SvtxHitMap_v1),sizeof(SvtxHitMap_v1),-1,294656,(char*)NULL,G__setup_memvarSvtxHitMap_v1,G__setup_memfuncSvtxHitMap_v1);
}
extern "C" void G__cpp_setupSvtxHitMap_v1_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupSvtxHitMap_v1_Dict()");
  G__set_cpp_environmentSvtxHitMap_v1_Dict();
  G__cpp_setup_tagtableSvtxHitMap_v1_Dict();

  G__cpp_setup_inheritanceSvtxHitMap_v1_Dict();

  G__cpp_setup_typetableSvtxHitMap_v1_Dict();

  G__cpp_setup_memvarSvtxHitMap_v1_Dict();

  G__cpp_setup_memfuncSvtxHitMap_v1_Dict();
  G__cpp_setup_globalSvtxHitMap_v1_Dict();
  G__cpp_setup_funcSvtxHitMap_v1_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncSvtxHitMap_v1_Dict();
  return;
}
class G__cpp_setup_initSvtxHitMap_v1_Dict {
  public:
    G__cpp_setup_initSvtxHitMap_v1_Dict() { G__add_setup_func("SvtxHitMap_v1_Dict",(G__incsetup)(&G__cpp_setupSvtxHitMap_v1_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initSvtxHitMap_v1_Dict() { G__remove_setup_func("SvtxHitMap_v1_Dict"); }
};
G__cpp_setup_initSvtxHitMap_v1_Dict G__cpp_setup_initializerSvtxHitMap_v1_Dict;

