//
// File generated by rootcint at Tue Mar 28 22:26:27 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME SvtxHit_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "SvtxHit_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void SvtxHit_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_SvtxHit(void *p);
   static void deleteArray_SvtxHit(void *p);
   static void destruct_SvtxHit(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::SvtxHit*)
   {
      ::SvtxHit *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::SvtxHit >(0);
      static ::ROOT::TGenericClassInfo 
         instance("SvtxHit", ::SvtxHit::Class_Version(), "./SvtxHit.h", 9,
                  typeid(::SvtxHit), ::ROOT::DefineBehavior(ptr, ptr),
                  &::SvtxHit::Dictionary, isa_proxy, 4,
                  sizeof(::SvtxHit) );
      instance.SetDelete(&delete_SvtxHit);
      instance.SetDeleteArray(&deleteArray_SvtxHit);
      instance.SetDestructor(&destruct_SvtxHit);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::SvtxHit*)
   {
      return GenerateInitInstanceLocal((::SvtxHit*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SvtxHit*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr SvtxHit::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *SvtxHit::Class_Name()
{
   return "SvtxHit";
}

//______________________________________________________________________________
const char *SvtxHit::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SvtxHit*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int SvtxHit::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SvtxHit*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void SvtxHit::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SvtxHit*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *SvtxHit::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SvtxHit*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void SvtxHit::Streamer(TBuffer &R__b)
{
   // Stream an object of class SvtxHit.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(SvtxHit::Class(),this);
   } else {
      R__b.WriteClassBuffer(SvtxHit::Class(),this);
   }
}

//______________________________________________________________________________
void SvtxHit::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class SvtxHit.
      TClass *R__cl = ::SvtxHit::IsA();
      if (R__cl || R__insp.IsA()) { }
      PHObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_SvtxHit(void *p) {
      delete ((::SvtxHit*)p);
   }
   static void deleteArray_SvtxHit(void *p) {
      delete [] ((::SvtxHit*)p);
   }
   static void destruct_SvtxHit(void *p) {
      typedef ::SvtxHit current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::SvtxHit

/********************************************************
* SvtxHit_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableSvtxHit_Dict();

extern "C" void G__set_cpp_environmentSvtxHit_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("SvtxHit.h");
  G__cpp_reset_tagtableSvtxHit_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevSvtxHit_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SvtxHit */
static int G__SvtxHit_Dict_177_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const SvtxHit*) G__getstructoffset())->Clone());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const SvtxHit*) G__getstructoffset())->get_id());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxHit*) G__getstructoffset())->set_id((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const SvtxHit*) G__getstructoffset())->get_layer());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxHit*) G__getstructoffset())->set_layer((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const SvtxHit*) G__getstructoffset())->get_adc());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxHit*) G__getstructoffset())->set_adc((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const SvtxHit*) G__getstructoffset())->get_e());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxHit*) G__getstructoffset())->set_e((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letULonglong(result7, 109, (G__uint64) ((const SvtxHit*) G__getstructoffset())->get_cellid());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxHit*) G__getstructoffset())->set_cellid((PHG4CellDefs::keytype) G__ULonglong(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) SvtxHit::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SvtxHit::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) SvtxHit::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SvtxHit::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxHit*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SvtxHit::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SvtxHit::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SvtxHit::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxHit_Dict_177_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SvtxHit::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__SvtxHit_Dict_177_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   SvtxHit* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new SvtxHit(*(SvtxHit*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SvtxHit_DictLN_SvtxHit));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SvtxHit G__TSvtxHit;
static int G__SvtxHit_Dict_177_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SvtxHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SvtxHit*) (soff+(sizeof(SvtxHit)*i)))->~G__TSvtxHit();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SvtxHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SvtxHit*) (soff))->~G__TSvtxHit();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__SvtxHit_Dict_177_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SvtxHit* dest = (SvtxHit*) G__getstructoffset();
   *dest = *(SvtxHit*) libp->para[0].ref;
   const SvtxHit& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SvtxHit */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncSvtxHit_Dict {
 public:
  G__Sizep2memfuncSvtxHit_Dict(): p(&G__Sizep2memfuncSvtxHit_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncSvtxHit_Dict::*p)();
};

size_t G__get_sizep2memfuncSvtxHit_Dict()
{
  G__Sizep2memfuncSvtxHit_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceSvtxHit_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__SvtxHit_DictLN_SvtxHit))) {
     SvtxHit *G__Lderived;
     G__Lderived=(SvtxHit*)0x1000;
     {
       PHObject *G__Lpbase=(PHObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SvtxHit_DictLN_SvtxHit),G__get_linked_tagnum(&G__SvtxHit_DictLN_PHObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SvtxHit_DictLN_SvtxHit),G__get_linked_tagnum(&G__SvtxHit_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableSvtxHit_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SvtxHit_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SvtxHit_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SvtxHit_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SvtxHit_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SvtxHit_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__SvtxHit_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SvtxHit_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SvtxHit_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SvtxHit_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SvtxHit_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SvtxHit */
static void G__setup_memvarSvtxHit(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SvtxHit_DictLN_SvtxHit));
   { SvtxHit *p; p=(SvtxHit*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SvtxHit_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarSvtxHit_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSvtxHit(void) {
   /* SvtxHit */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SvtxHit_DictLN_SvtxHit));
   G__memfunc_setup("identify",860,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 8, "u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 'std::cout' os", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Reset",515,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("isValid",716,(G__InterfaceMethod) NULL,105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Clone",497,G__SvtxHit_Dict_177_0_4, 85, G__get_linked_tagnum(&G__SvtxHit_DictLN_SvtxHit), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_id",620,G__SvtxHit_Dict_177_0_5, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_id",632,G__SvtxHit_Dict_177_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - id", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_layer",956,G__SvtxHit_Dict_177_0_7, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_layer",968,G__SvtxHit_Dict_177_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - layer", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_adc",711,G__SvtxHit_Dict_177_0_9, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_adc",723,G__SvtxHit_Dict_177_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - adc", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_e",516,G__SvtxHit_Dict_177_0_11, 102, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_e",528,G__SvtxHit_Dict_177_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - e", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_cellid",1036,G__SvtxHit_Dict_177_0_13, 109, -1, G__defined_typename("PHG4CellDefs::keytype"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_cellid",1048,G__SvtxHit_Dict_177_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "m - 'PHG4CellDefs::keytype' 0 - cellid", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SvtxHit",730,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__SvtxHit_DictLN_SvtxHit), -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__SvtxHit_Dict_177_0_16, 85, G__get_linked_tagnum(&G__SvtxHit_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&SvtxHit::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__SvtxHit_Dict_177_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SvtxHit::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__SvtxHit_Dict_177_0_18, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&SvtxHit::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__SvtxHit_Dict_177_0_19, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&SvtxHit::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__SvtxHit_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__SvtxHit_Dict_177_0_23, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__SvtxHit_Dict_177_0_24, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SvtxHit::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__SvtxHit_Dict_177_0_25, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SvtxHit::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__SvtxHit_Dict_177_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SvtxHit::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__SvtxHit_Dict_177_0_27, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SvtxHit::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("SvtxHit", 730, G__SvtxHit_Dict_177_0_28, (int) ('i'), G__get_linked_tagnum(&G__SvtxHit_DictLN_SvtxHit), -1, 0, 1, 1, 1, 0, "u 'SvtxHit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~SvtxHit", 856, G__SvtxHit_Dict_177_0_29, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__SvtxHit_Dict_177_0_30, (int) ('u'), G__get_linked_tagnum(&G__SvtxHit_DictLN_SvtxHit), -1, 1, 1, 1, 1, 0, "u 'SvtxHit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncSvtxHit_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalSvtxHit_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcSvtxHit_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__SvtxHit_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__SvtxHit_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__SvtxHit_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__SvtxHit_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__SvtxHit_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR = { "basic_ostream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__SvtxHit_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__SvtxHit_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SvtxHit_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__SvtxHit_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SvtxHit_DictLN_PHObject = { "PHObject" , 99 , -1 };
G__linked_taginfo G__SvtxHit_DictLN_SvtxHit = { "SvtxHit" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableSvtxHit_Dict() {
  G__SvtxHit_DictLN_TClass.tagnum = -1 ;
  G__SvtxHit_DictLN_TBuffer.tagnum = -1 ;
  G__SvtxHit_DictLN_TMemberInspector.tagnum = -1 ;
  G__SvtxHit_DictLN_TObject.tagnum = -1 ;
  G__SvtxHit_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__SvtxHit_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__SvtxHit_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SvtxHit_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__SvtxHit_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SvtxHit_DictLN_PHObject.tagnum = -1 ;
  G__SvtxHit_DictLN_SvtxHit.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableSvtxHit_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__SvtxHit_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__SvtxHit_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__SvtxHit_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__SvtxHit_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__SvtxHit_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__SvtxHit_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__SvtxHit_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SvtxHit_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SvtxHit_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SvtxHit_DictLN_PHObject);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SvtxHit_DictLN_SvtxHit),sizeof(SvtxHit),-1,292096,(char*)NULL,G__setup_memvarSvtxHit,G__setup_memfuncSvtxHit);
}
extern "C" void G__cpp_setupSvtxHit_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupSvtxHit_Dict()");
  G__set_cpp_environmentSvtxHit_Dict();
  G__cpp_setup_tagtableSvtxHit_Dict();

  G__cpp_setup_inheritanceSvtxHit_Dict();

  G__cpp_setup_typetableSvtxHit_Dict();

  G__cpp_setup_memvarSvtxHit_Dict();

  G__cpp_setup_memfuncSvtxHit_Dict();
  G__cpp_setup_globalSvtxHit_Dict();
  G__cpp_setup_funcSvtxHit_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncSvtxHit_Dict();
  return;
}
class G__cpp_setup_initSvtxHit_Dict {
  public:
    G__cpp_setup_initSvtxHit_Dict() { G__add_setup_func("SvtxHit_Dict",(G__incsetup)(&G__cpp_setupSvtxHit_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initSvtxHit_Dict() { G__remove_setup_func("SvtxHit_Dict"); }
};
G__cpp_setup_initSvtxHit_Dict G__cpp_setup_initializerSvtxHit_Dict;

