/********************************************************************
* SvtxTrack_v1_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SvtxTrack_v1_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSvtxTrack_v1_Dict();
extern void G__cpp_setup_inheritanceSvtxTrack_v1_Dict();
extern void G__cpp_setup_typetableSvtxTrack_v1_Dict();
extern void G__cpp_setup_memvarSvtxTrack_v1_Dict();
extern void G__cpp_setup_globalSvtxTrack_v1_Dict();
extern void G__cpp_setup_memfuncSvtxTrack_v1_Dict();
extern void G__cpp_setup_funcSvtxTrack_v1_Dict();
extern void G__set_cpp_environmentSvtxTrack_v1_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "SvtxTrack_v1.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SvtxTrack_v1_DictLN_TClass;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_TBuffer;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_TMemberInspector;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_TObject;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_PHObject;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_SvtxTrackState;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_SvtxTrack;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_maplEfloatcOSvtxTrackStatemUcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOSvtxTrackStatemUgRsPgRsPgR;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_maplEfloatcOSvtxTrackStatemUcOlesslEfloatgRcOallocatorlEpairlEconstsPfloatcOSvtxTrackStatemUgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgRcLcLiterator;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_SvtxTrackcLcLCAL_LAYER;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_SvtxTrack_v1;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_maplESvtxTrackcLcLCAL_LAYERcOfloatcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOfloatgRsPgRsPgR;
extern G__linked_taginfo G__SvtxTrack_v1_DictLN_maplESvtxTrackcLcLCAL_LAYERcOintcOlesslESvtxTrackcLcLCAL_LAYERgRcOallocatorlEpairlEconstsPSvtxTrackcLcLCAL_LAYERcOintgRsPgRsPgR;

/* STUB derived class for protected member access */
