//
// File generated by rootcint at Tue Mar 28 22:26:28 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME SvtxCluster_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "SvtxCluster_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void SvtxCluster_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_SvtxCluster(void *p);
   static void deleteArray_SvtxCluster(void *p);
   static void destruct_SvtxCluster(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::SvtxCluster*)
   {
      ::SvtxCluster *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::SvtxCluster >(0);
      static ::ROOT::TGenericClassInfo 
         instance("SvtxCluster", ::SvtxCluster::Class_Version(), "./SvtxCluster.h", 10,
                  typeid(::SvtxCluster), ::ROOT::DefineBehavior(ptr, ptr),
                  &::SvtxCluster::Dictionary, isa_proxy, 4,
                  sizeof(::SvtxCluster) );
      instance.SetDelete(&delete_SvtxCluster);
      instance.SetDeleteArray(&deleteArray_SvtxCluster);
      instance.SetDestructor(&destruct_SvtxCluster);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::SvtxCluster*)
   {
      return GenerateInitInstanceLocal((::SvtxCluster*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SvtxCluster*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr SvtxCluster::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *SvtxCluster::Class_Name()
{
   return "SvtxCluster";
}

//______________________________________________________________________________
const char *SvtxCluster::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SvtxCluster*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int SvtxCluster::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::SvtxCluster*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void SvtxCluster::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SvtxCluster*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *SvtxCluster::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::SvtxCluster*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void SvtxCluster::Streamer(TBuffer &R__b)
{
   // Stream an object of class SvtxCluster.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(SvtxCluster::Class(),this);
   } else {
      R__b.WriteClassBuffer(SvtxCluster::Class(),this);
   }
}

//______________________________________________________________________________
void SvtxCluster::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class SvtxCluster.
      TClass *R__cl = ::SvtxCluster::IsA();
      if (R__cl || R__insp.IsA()) { }
      PHObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_SvtxCluster(void *p) {
      delete ((::SvtxCluster*)p);
   }
   static void deleteArray_SvtxCluster(void *p) {
      delete [] ((::SvtxCluster*)p);
   }
   static void destruct_SvtxCluster(void *p) {
      typedef ::SvtxCluster current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::SvtxCluster

/********************************************************
* SvtxCluster_Dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableSvtxCluster_Dict();

extern "C" void G__set_cpp_environmentSvtxCluster_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("SvtxCluster.h");
  G__cpp_reset_tagtableSvtxCluster_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevSvtxCluster_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SvtxCluster */
static int G__SvtxCluster_Dict_234_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const SvtxCluster*) G__getstructoffset())->Clone());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const SvtxCluster*) G__getstructoffset())->get_id());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxCluster*) G__getstructoffset())->set_id((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const SvtxCluster*) G__getstructoffset())->get_layer());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxCluster*) G__getstructoffset())->set_layer((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const SvtxCluster*) G__getstructoffset())->get_x());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxCluster*) G__getstructoffset())->set_x((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const SvtxCluster*) G__getstructoffset())->get_y());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxCluster*) G__getstructoffset())->set_y((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const SvtxCluster*) G__getstructoffset())->get_z());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxCluster*) G__getstructoffset())->set_z((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const SvtxCluster*) G__getstructoffset())->get_position((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxCluster*) G__getstructoffset())->set_position((int) G__int(libp->para[0]), (float) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const SvtxCluster*) G__getstructoffset())->get_e());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxCluster*) G__getstructoffset())->set_e((float) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((const SvtxCluster*) G__getstructoffset())->get_adc());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxCluster*) G__getstructoffset())->set_adc((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const SvtxCluster*) G__getstructoffset())->get_size((unsigned int) G__int(libp->para[0]), (unsigned int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxCluster*) G__getstructoffset())->set_size((unsigned int) G__int(libp->para[0]), (unsigned int) G__int(libp->para[1])
, (float) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const SvtxCluster*) G__getstructoffset())->get_error((unsigned int) G__int(libp->para[0]), (unsigned int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxCluster*) G__getstructoffset())->set_error((unsigned int) G__int(libp->para[0]), (unsigned int) G__int(libp->para[1])
, (float) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxCluster*) G__getstructoffset())->clear_hits();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((SvtxCluster*) G__getstructoffset())->empty_hits());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((SvtxCluster*) G__getstructoffset())->size_hits());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxCluster*) G__getstructoffset())->insert_hit((unsigned int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((SvtxCluster*) G__getstructoffset())->erase_hit((unsigned int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const SvtxCluster::ConstHitIter* pobj;
         const SvtxCluster::ConstHitIter xobj = ((const SvtxCluster*) G__getstructoffset())->begin_hits();
         pobj = new SvtxCluster::ConstHitIter(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const SvtxCluster::ConstHitIter* pobj;
         const SvtxCluster::ConstHitIter xobj = ((const SvtxCluster*) G__getstructoffset())->find_hit((unsigned int) G__int(libp->para[0]));
         pobj = new SvtxCluster::ConstHitIter(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const SvtxCluster::ConstHitIter* pobj;
         const SvtxCluster::ConstHitIter xobj = ((const SvtxCluster*) G__getstructoffset())->end_hits();
         pobj = new SvtxCluster::ConstHitIter(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         SvtxCluster::HitIter* pobj;
         SvtxCluster::HitIter xobj = ((SvtxCluster*) G__getstructoffset())->begin_hits();
         pobj = new SvtxCluster::HitIter(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         SvtxCluster::HitIter* pobj;
         SvtxCluster::HitIter xobj = ((SvtxCluster*) G__getstructoffset())->find_hit((unsigned int) G__int(libp->para[0]));
         pobj = new SvtxCluster::HitIter(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         SvtxCluster::HitIter* pobj;
         SvtxCluster::HitIter xobj = ((SvtxCluster*) G__getstructoffset())->end_hits();
         pobj = new SvtxCluster::HitIter(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const SvtxCluster*) G__getstructoffset())->get_phi_size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const SvtxCluster*) G__getstructoffset())->get_z_size());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const SvtxCluster*) G__getstructoffset())->get_phi_error());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((const SvtxCluster*) G__getstructoffset())->get_z_error());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) SvtxCluster::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SvtxCluster::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) SvtxCluster::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SvtxCluster::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SvtxCluster*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SvtxCluster::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SvtxCluster::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SvtxCluster::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__SvtxCluster_Dict_234_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SvtxCluster::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__SvtxCluster_Dict_234_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   SvtxCluster* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new SvtxCluster(*(SvtxCluster*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__SvtxCluster_DictLN_SvtxCluster));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SvtxCluster G__TSvtxCluster;
static int G__SvtxCluster_Dict_234_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SvtxCluster*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SvtxCluster*) (soff+(sizeof(SvtxCluster)*i)))->~G__TSvtxCluster();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SvtxCluster*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SvtxCluster*) (soff))->~G__TSvtxCluster();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__SvtxCluster_Dict_234_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SvtxCluster* dest = (SvtxCluster*) G__getstructoffset();
   *dest = *(SvtxCluster*) libp->para[0].ref;
   const SvtxCluster& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SvtxCluster */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncSvtxCluster_Dict {
 public:
  G__Sizep2memfuncSvtxCluster_Dict(): p(&G__Sizep2memfuncSvtxCluster_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncSvtxCluster_Dict::*p)();
};

size_t G__get_sizep2memfuncSvtxCluster_Dict()
{
  G__Sizep2memfuncSvtxCluster_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceSvtxCluster_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__SvtxCluster_DictLN_SvtxCluster))) {
     SvtxCluster *G__Lderived;
     G__Lderived=(SvtxCluster*)0x1000;
     {
       PHObject *G__Lpbase=(PHObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SvtxCluster_DictLN_SvtxCluster),G__get_linked_tagnum(&G__SvtxCluster_DictLN_PHObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__SvtxCluster_DictLN_SvtxCluster),G__get_linked_tagnum(&G__SvtxCluster_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableSvtxCluster_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__SvtxCluster_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SvtxCluster_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SvtxCluster_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SvtxCluster_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SvtxCluster_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__SvtxCluster_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__SvtxCluster_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SvtxCluster_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__SvtxCluster_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__SvtxCluster_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<unsigned int>",117,G__get_linked_tagnum(&G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<unsigned int,less<unsigned int> >",117,G__get_linked_tagnum(&G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("HitSet",117,G__get_linked_tagnum(&G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR),0,G__get_linked_tagnum(&G__SvtxCluster_DictLN_SvtxCluster));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ConstHitIter",117,G__get_linked_tagnum(&G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__SvtxCluster_DictLN_SvtxCluster));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("HitIter",117,G__get_linked_tagnum(&G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgRcLcLiterator),0,G__get_linked_tagnum(&G__SvtxCluster_DictLN_SvtxCluster));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SvtxCluster */
static void G__setup_memvarSvtxCluster(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__SvtxCluster_DictLN_SvtxCluster));
   { SvtxCluster *p; p=(SvtxCluster*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__SvtxCluster_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarSvtxCluster_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSvtxCluster(void) {
   /* SvtxCluster */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__SvtxCluster_DictLN_SvtxCluster));
   G__memfunc_setup("identify",860,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 8, "u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 'std::cout' os", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Reset",515,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("isValid",716,(G__InterfaceMethod) NULL,105, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Clone",497,G__SvtxCluster_Dict_234_0_4, 85, G__get_linked_tagnum(&G__SvtxCluster_DictLN_SvtxCluster), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_id",620,G__SvtxCluster_Dict_234_0_5, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_id",632,G__SvtxCluster_Dict_234_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - id", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_layer",956,G__SvtxCluster_Dict_234_0_7, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_layer",968,G__SvtxCluster_Dict_234_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - layer", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_x",535,G__SvtxCluster_Dict_234_0_9, 102, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_x",547,G__SvtxCluster_Dict_234_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - x", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_y",536,G__SvtxCluster_Dict_234_0_11, 102, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_y",548,G__SvtxCluster_Dict_234_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - y", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_z",537,G__SvtxCluster_Dict_234_0_13, 102, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_z",549,G__SvtxCluster_Dict_234_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - z", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_position",1300,G__SvtxCluster_Dict_234_0_15, 102, -1, -1, 0, 1, 1, 1, 8, "i - - 0 - coor", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_position",1312,G__SvtxCluster_Dict_234_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - coor f - - 0 - xi", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_e",516,G__SvtxCluster_Dict_234_0_17, 102, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_e",528,G__SvtxCluster_Dict_234_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "f - - 0 - e", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_adc",711,G__SvtxCluster_Dict_234_0_19, 104, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_adc",723,G__SvtxCluster_Dict_234_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - adc", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_size",858,G__SvtxCluster_Dict_234_0_21, 102, -1, -1, 0, 2, 1, 1, 8, 
"h - - 0 - i h - - 0 - j", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_size",870,G__SvtxCluster_Dict_234_0_22, 121, -1, -1, 0, 3, 1, 1, 0, 
"h - - 0 - i h - - 0 - j "
"f - - 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_error",969,G__SvtxCluster_Dict_234_0_23, 102, -1, -1, 0, 2, 1, 1, 8, 
"h - - 0 - i h - - 0 - j", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("set_error",981,G__SvtxCluster_Dict_234_0_24, 121, -1, -1, 0, 3, 1, 1, 0, 
"h - - 0 - i h - - 0 - j "
"f - - 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("clear_hits",1054,G__SvtxCluster_Dict_234_0_25, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("empty_hits",1094,G__SvtxCluster_Dict_234_0_26, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("size_hits",978,G__SvtxCluster_Dict_234_0_27, 107, -1, G__defined_typename("size_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("insert_hit",1081,G__SvtxCluster_Dict_234_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "h - - 0 - hit_id", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("erase_hit",948,G__SvtxCluster_Dict_234_0_29, 107, -1, G__defined_typename("size_t"), 0, 1, 1, 1, 0, "h - - 0 - hit_id", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("begin_hits",1052,G__SvtxCluster_Dict_234_0_30, 117, G__get_linked_tagnum(&G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgRcLcLiterator), G__defined_typename("SvtxCluster::ConstHitIter"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("find_hit",837,G__SvtxCluster_Dict_234_0_31, 117, G__get_linked_tagnum(&G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgRcLcLiterator), G__defined_typename("SvtxCluster::ConstHitIter"), 0, 1, 1, 1, 8, "h - - 0 - hitid", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("end_hits",846,G__SvtxCluster_Dict_234_0_32, 117, G__get_linked_tagnum(&G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgRcLcLiterator), G__defined_typename("SvtxCluster::ConstHitIter"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("begin_hits",1052,G__SvtxCluster_Dict_234_0_33, 117, G__get_linked_tagnum(&G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgRcLcLiterator), G__defined_typename("SvtxCluster::HitIter"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("find_hit",837,G__SvtxCluster_Dict_234_0_34, 117, G__get_linked_tagnum(&G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgRcLcLiterator), G__defined_typename("SvtxCluster::HitIter"), 0, 1, 1, 1, 0, "h - - 0 - hitid", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("end_hits",846,G__SvtxCluster_Dict_234_0_35, 117, G__get_linked_tagnum(&G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgRcLcLiterator), G__defined_typename("SvtxCluster::HitIter"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_phi_size",1274,G__SvtxCluster_Dict_234_0_36, 102, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_z_size",1075,G__SvtxCluster_Dict_234_0_37, 102, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_phi_error",1385,G__SvtxCluster_Dict_234_0_38, 102, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("get_z_error",1186,G__SvtxCluster_Dict_234_0_39, 102, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SvtxCluster",1175,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__SvtxCluster_DictLN_SvtxCluster), -1, 0, 0, 1, 2, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__SvtxCluster_Dict_234_0_41, 85, G__get_linked_tagnum(&G__SvtxCluster_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&SvtxCluster::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__SvtxCluster_Dict_234_0_42, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SvtxCluster::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__SvtxCluster_Dict_234_0_43, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&SvtxCluster::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__SvtxCluster_Dict_234_0_44, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&SvtxCluster::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__SvtxCluster_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__SvtxCluster_Dict_234_0_48, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__SvtxCluster_Dict_234_0_49, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SvtxCluster::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__SvtxCluster_Dict_234_0_50, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SvtxCluster::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__SvtxCluster_Dict_234_0_51, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SvtxCluster::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__SvtxCluster_Dict_234_0_52, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SvtxCluster::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("SvtxCluster", 1175, G__SvtxCluster_Dict_234_0_53, (int) ('i'), G__get_linked_tagnum(&G__SvtxCluster_DictLN_SvtxCluster), -1, 0, 1, 1, 1, 0, "u 'SvtxCluster' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~SvtxCluster", 1301, G__SvtxCluster_Dict_234_0_54, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__SvtxCluster_Dict_234_0_55, (int) ('u'), G__get_linked_tagnum(&G__SvtxCluster_DictLN_SvtxCluster), -1, 1, 1, 1, 1, 0, "u 'SvtxCluster' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncSvtxCluster_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalSvtxCluster_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcSvtxCluster_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__SvtxCluster_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__SvtxCluster_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__SvtxCluster_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__SvtxCluster_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__SvtxCluster_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR = { "basic_ostream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__SvtxCluster_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__SvtxCluster_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SvtxCluster_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__SvtxCluster_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__SvtxCluster_DictLN_PHObject = { "PHObject" , 99 , -1 };
G__linked_taginfo G__SvtxCluster_DictLN_SvtxCluster = { "SvtxCluster" , 99 , -1 };
G__linked_taginfo G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR = { "set<unsigned int,less<unsigned int>,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgRcLcLiterator = { "set<unsigned int,less<unsigned int>,allocator<unsigned int> >::iterator" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableSvtxCluster_Dict() {
  G__SvtxCluster_DictLN_TClass.tagnum = -1 ;
  G__SvtxCluster_DictLN_TBuffer.tagnum = -1 ;
  G__SvtxCluster_DictLN_TMemberInspector.tagnum = -1 ;
  G__SvtxCluster_DictLN_TObject.tagnum = -1 ;
  G__SvtxCluster_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__SvtxCluster_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__SvtxCluster_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SvtxCluster_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__SvtxCluster_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__SvtxCluster_DictLN_PHObject.tagnum = -1 ;
  G__SvtxCluster_DictLN_SvtxCluster.tagnum = -1 ;
  G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgRcLcLiterator.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableSvtxCluster_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__SvtxCluster_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__SvtxCluster_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__SvtxCluster_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__SvtxCluster_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__SvtxCluster_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__SvtxCluster_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__SvtxCluster_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SvtxCluster_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__SvtxCluster_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__SvtxCluster_DictLN_PHObject);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__SvtxCluster_DictLN_SvtxCluster),sizeof(SvtxCluster),-1,292096,(char*)NULL,G__setup_memvarSvtxCluster,G__setup_memfuncSvtxCluster);
   G__get_linked_tagnum_fwd(&G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__SvtxCluster_DictLN_setlEunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEunsignedsPintgRsPgRcLcLiterator);
}
extern "C" void G__cpp_setupSvtxCluster_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupSvtxCluster_Dict()");
  G__set_cpp_environmentSvtxCluster_Dict();
  G__cpp_setup_tagtableSvtxCluster_Dict();

  G__cpp_setup_inheritanceSvtxCluster_Dict();

  G__cpp_setup_typetableSvtxCluster_Dict();

  G__cpp_setup_memvarSvtxCluster_Dict();

  G__cpp_setup_memfuncSvtxCluster_Dict();
  G__cpp_setup_globalSvtxCluster_Dict();
  G__cpp_setup_funcSvtxCluster_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncSvtxCluster_Dict();
  return;
}
class G__cpp_setup_initSvtxCluster_Dict {
  public:
    G__cpp_setup_initSvtxCluster_Dict() { G__add_setup_func("SvtxCluster_Dict",(G__incsetup)(&G__cpp_setupSvtxCluster_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initSvtxCluster_Dict() { G__remove_setup_func("SvtxCluster_Dict"); }
};
G__cpp_setup_initSvtxCluster_Dict G__cpp_setup_initializerSvtxCluster_Dict;

