
/***********************************************************************
* Copyright 1998-2020 CERN for the benefit of the EvtGen authors       *
*                                                                      *
* This file is part of EvtGen.                                         *
*                                                                      *
* EvtGen is free software: you can redistribute it and/or modify       *
* it under the terms of the GNU General Public License as published by *
* the Free Software Foundation, either version 3 of the License, or    *
* (at your option) any later version.                                  *
*                                                                      *
* EvtGen is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of       *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
* GNU General Public License for more details.                         *
*                                                                      *
* You should have received a copy of the GNU General Public License    *
* along with EvtGen.  If not, see <https://www.gnu.org/licenses/>.     *
***********************************************************************/

{
TFile *myFile = new TFile("dstarpi.root","READ");
myFile->ls();

TCanvas *myCanvas = new TCanvas("c","dstarpi",0,0,600,600);
myCanvas->Divide(2,3);

TH1F *th1=h1;
TH1F *th2=h2;
TH1F *th3=h3;
TH1F *th4=h4;
TH1F *th5=h5;

TH1F* sum=new TH1F(*h2+*h5);
TH1F* diff=new TH1F(*h2-*h5);
TH1F* asym=new TH1F((*diff)/(*sum));

TH1F* suma=new TH1F(*h3+*h4);
TH1F* diffa=new TH1F(*h3-*h4);
TH1F* asyma=new TH1F((*diffa)/(*suma));




myCanvas->cd(1);
th2->Draw();
th5->Draw("SAME");
myCanvas.Update();

myCanvas->cd(2);
th3->Draw();
th4->Draw("SAME");
myCanvas.Update();

myCanvas->cd(3);
th4->Draw();
myCanvas.Update();

myCanvas->cd(4);
th5->Draw();
myCanvas.Update();

myCanvas->cd(5);
asym->Draw();
myCanvas.Update();

myCanvas->cd(6);
asyma->Draw();
myCanvas.Update();


myCanvas->Print("ssdcp.eps");



}

