
/***********************************************************************
* Copyright 1998-2020 CERN for the benefit of the EvtGen authors       *
*                                                                      *
* This file is part of EvtGen.                                         *
*                                                                      *
* EvtGen is free software: you can redistribute it and/or modify       *
* it under the terms of the GNU General Public License as published by *
* the Free Software Foundation, either version 3 of the License, or    *
* (at your option) any later version.                                  *
*                                                                      *
* EvtGen is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of       *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
* GNU General Public License for more details.                         *
*                                                                      *
* You should have received a copy of the GNU General Public License    *
* along with EvtGen.  If not, see <https://www.gnu.org/licenses/>.     *
***********************************************************************/

void helamp1(TString filenamebase){

TFile *myFile = new TFile(filenamebase+".root","READ");
myFile->ls();

TCanvas *myCanvas = new TCanvas("c",filenamebase,0,0,800,800);
myCanvas->Divide(2,2);

TH1F *th1=h1;

TF1 *f1=new TF1("f1", "[0]*(1.0+[1]*x+[2]*x*x+[3]*x*x*x+[4]*x*x*x*x)/(2+[2]+0.5*[4])",-1.0,1.0);

myCanvas->cd(1);
th1->Fit("f1");


TH1F *th2=h2;

TF1 *f2=new TF1("f2", "[0]*(1.0+[1]*x+[2]*x*x+[3]*x*x*x+[4]*x*x*x*x)/(2+[2]*0.5*[4])",-1.0,1.0);

myCanvas->cd(2);
th2->Fit("f2");



myCanvas.Update();

myCanvas->Print(filenamebase+".eps");

}

