
/***********************************************************************
* Copyright 1998-2020 CERN for the benefit of the EvtGen authors       *
*                                                                      *
* This file is part of EvtGen.                                         *
*                                                                      *
* EvtGen is free software: you can redistribute it and/or modify       *
* it under the terms of the GNU General Public License as published by *
* the Free Software Foundation, either version 3 of the License, or    *
* (at your option) any later version.                                  *
*                                                                      *
* EvtGen is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of       *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
* GNU General Public License for more details.                         *
*                                                                      *
* You should have received a copy of the GNU General Public License    *
* along with EvtGen.  If not, see <https://www.gnu.org/licenses/>.     *
***********************************************************************/

{
TFile *myFile = new TFile("jpsif0gamma.root","READ");
myFile->ls();

TCanvas *myCanvas = new TCanvas("c","JpsiXgamma",0,0,600,400);
myCanvas->Divide(2,2);
myCanvas->cd(1);


Int_t type=111;

TH1F *h1=h1;
TH1F *h2=h2;
TH1F *h3=h3;


h1->Draw();
myCanvas.Update();
myCanvas->cd(2);
h2->Draw();
myCanvas.Update();
myCanvas->cd(3);
h3->Draw();
myCanvas.Update();

myCanvas->Print("jpsif0gamma.eps");

}
