
/***********************************************************************
* Copyright 1998-2020 CERN for the benefit of the EvtGen authors       *
*                                                                      *
* This file is part of EvtGen.                                         *
*                                                                      *
* EvtGen is free software: you can redistribute it and/or modify       *
* it under the terms of the GNU General Public License as published by *
* the Free Software Foundation, either version 3 of the License, or    *
* (at your option) any later version.                                  *
*                                                                      *
* EvtGen is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of       *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
* GNU General Public License for more details.                         *
*                                                                      *
* You should have received a copy of the GNU General Public License    *
* along with EvtGen.  If not, see <https://www.gnu.org/licenses/>.     *
***********************************************************************/

{
TFile *myFile = new TFile("jpsipolar.root","READ");
myFile->ls();
TCanvas *myCanvas = new TCanvas("c","JPSIPOLAR",0,0,400,600);
myCanvas->Divide(1,3);
myCanvas->cd(1);
  
TH1F *hist1=h1;
TH1F *hist2=h2;
TH1F *hist3=h3;

TF1 *f1=new TF1("f1", "[0]*(1.0 + [1]*x*x)",-1.0,1.0); 
f1->SetParameters(1,0);
hist1->Fit("f1");
myCanvas->cd(2);
hist2->Fit("f1");
myCanvas->cd(3);
hist3->Fit("f1");

myCanvas.Update();

myCanvas->Print("jpsipolar.eps");

}
