
/***********************************************************************
* Copyright 1998-2020 CERN for the benefit of the EvtGen authors       *
*                                                                      *
* This file is part of EvtGen.                                         *
*                                                                      *
* EvtGen is free software: you can redistribute it and/or modify       *
* it under the terms of the GNU General Public License as published by *
* the Free Software Foundation, either version 3 of the License, or    *
* (at your option) any later version.                                  *
*                                                                      *
* EvtGen is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of       *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
* GNU General Public License for more details.                         *
*                                                                      *
* You should have received a copy of the GNU General Public License    *
* along with EvtGen.  If not, see <https://www.gnu.org/licenses/>.     *
***********************************************************************/

{
gROOT->SetStyle("Plain");
Int_t nbin(31);

Double_t p[nbin]={0.225,0.275,0.325,0.375,
	0.425,0.475,0.525,0.575,0.625,
	0.675,0.725,0.775,0.825,0.875,
	0.925,0.975,1.05,1.15,1.25,
	1.35,1.45,1.55,1.65,1.75,1.85,
	1.95,2.05,2.15,2.25,2.35,2.5};

Double_t ep[nbin]={0.025,0.025,0.025,0.025,
	0.025,0.025,0.025,0.025,0.025,
	0.025,0.025,0.025,0.025,0.025,
	0.025,0.025,0.05,0.05,0.05,
	0.05,0.05,0.05,0.05,0.05,0.05,
	0.05,0.05,0.05,0.05,0.05,0.1};

Double_t nkp[nbin]={1.1595,1.4215,1.5820,1.8461,	
	1.8675,1.9407,1.8511,1.8411,1.7194,1.5651,
	1.4151,1.2614,1.1933,1.0454,0.8693,0.7990,
	0.6432,0.4611,0.3595,0.2712,0.1971,0.1489,
	0.1056,0.0849,0.0578,0.0331,0.0219,0.0160,
	0.0072,0.0064,0.0034};

Double_t etot[nbin]={0.0289,0.0327,0.0331,0.0380,0.0379,
	0.0411,0.0395,0.0423,0.0378,0.0345,0.0340,0.0287,
	0.0283,0.0236,0.0205,0.0216,0.0156,0.0142,0.0133,
	0.0113,0.0102,0.0087,0.0077,0.0068,0.0047,0.0044,
	0.0042,0.0036,0.0033,0.0025};

TFile *myFile = new TFile("generic.root","READ");

Float_t nBB=1.0/25000.;


TH1F *pipmom=new TH1F(*kp);
*pipmom=(*pipmom)*nBB;

TCanvas *myCanvas = new TCanvas("c","ssdcp",0,0,400,400);

//TH1F *th1=h1;

TGraphErrors *gr1=new TGraphErrors(nbin,p,nkp,ep,etot);

gr1->SetMarkerStyle(21);

gr1->SetMarkerSize(0.6);

gr1->SetMaximum(2.5);
gr1->SetTitle("");

Float_t lm=myCanvas->GetLeftMargin();
Float_t bm=myCanvas->GetBottomMargin();
lm=lm*1.5;
bm=bm*1.5;
myCanvas->SetLeftMargin(lm);
myCanvas->SetBottomMargin(bm);


gr1->Draw("AP");
pipmom->Draw("SAME");

TAxis *axisx=gr1->GetXaxis();
TAxis *axisy=gr1->GetYaxis();
axisx->SetLabelSize(0.06);
axisy->SetLabelSize(0.06);
axisx->SetTitleOffset(1.);
axisx->SetLimits(0.0,3.0);

TLine *line=new TLine(0.,0.,3.,0.);
line->Draw();

Float_t ts2=axisx->GetTitleSize();
ts2=1.5*ts2;
axisx->SetTitleSize(ts2);

axisx->SetTitle("Momentum (GeV/c)");

TLatex *myytit=new TLatex();
//axisy->SetTitle(myytit);

myytit->SetTextAngle(90);
Float_t ts=myytit->GetTextSize();
ts=1.3*ts;
myytit->SetTextSize(ts);

myytit->DrawLatex(-0.3,1.2,"1/#sigma_{#Upsilon(4S)} d#sigma/dp");

myCanvas->Print("kp.gif");



}


