
/***********************************************************************
* Copyright 1998-2020 CERN for the benefit of the EvtGen authors       *
*                                                                      *
* This file is part of EvtGen.                                         *
*                                                                      *
* EvtGen is free software: you can redistribute it and/or modify       *
* it under the terms of the GNU General Public License as published by *
* the Free Software Foundation, either version 3 of the License, or    *
* (at your option) any later version.                                  *
*                                                                      *
* EvtGen is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of       *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
* GNU General Public License for more details.                         *
*                                                                      *
* You should have received a copy of the GNU General Public License    *
* along with EvtGen.  If not, see <https://www.gnu.org/licenses/>.     *
***********************************************************************/

{
TFile *myFile = new TFile("kstarll.root","READ");
myFile->ls();
TCanvas *myCanvas = new TCanvas("c","KSTARLL",0,0,600,400);
myCanvas->Divide(2,2);
myCanvas->cd(1);

TH2F *hist1=h1;
TH1F *hist2=h2;

TH1F *hist7=h7;
TH1F *hist8=h8;

hist1->Draw();
myCanvas.Update();
myCanvas->cd(2);
hist2->Draw();
myCanvas.Update();

myCanvas->cd(3);
hist7->Draw();
myCanvas.Update();

myCanvas->cd(4);
hist8->Draw();
myCanvas.Update();


myCanvas->Print("kstarll.eps");

}
