
/***********************************************************************
* Copyright 1998-2020 CERN for the benefit of the EvtGen authors       *
*                                                                      *
* This file is part of EvtGen.                                         *
*                                                                      *
* EvtGen is free software: you can redistribute it and/or modify       *
* it under the terms of the GNU General Public License as published by *
* the Free Software Foundation, either version 3 of the License, or    *
* (at your option) any later version.                                  *
*                                                                      *
* EvtGen is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of       *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
* GNU General Public License for more details.                         *
*                                                                      *
* You should have received a copy of the GNU General Public License    *
* along with EvtGen.  If not, see <https://www.gnu.org/licenses/>.     *
***********************************************************************/

{
TFile *myFile = new TFile("vvpipi.root","READ");
myFile->ls();

TCanvas *myCanvas = new TCanvas("c","vvpipi",0,0,800,800);
myCanvas->Divide(2,3);

myCanvas->cd(1);
TH1F *th1=h1;
th1->Draw();

myCanvas->cd(2);
TH1F *th2=h2;
th2->Draw();

myCanvas->cd(3);
TH1F *th3=h3;
th3->Draw();

myCanvas->cd(4);
TH2F *th4=h4;
th4->Draw();

myCanvas->cd(5);
TH1F *th5=h5;
th5->Draw();

myCanvas->cd(6);
TH1F *th6=h6;
th6->Draw();

myCanvas.Update();

myCanvas->Print("vvpipi.eps");

}

