#ifndef __EVENT_TYPES_H
#define __EVENT_TYPES_H

#define DATAEVENT 1
#define DATA1EVENT 1
#define DATA2EVENT 2
#define DATA3EVENT 3
#define REJECTEDEVENT 7

#define SPILLONEVENT 8
#define BEGRUNEVENT 9
#define RUNINFOEVENT 11
#define ENDRUNEVENT 12
#define SCALEREVENT 14
#define SPILLOFFEVENT 16

#define CORRUPTEVENTMASK 0x400

#endif
