#ifndef __ONLMONHISTOBINDEFS_H__
#define __ONLMONHISTOBINDEFS_H__

enum {RUNNUMBERBIN = 1, 
      CURRENTTIMEBIN, 
      BORTIMEBIN, 
      EORTIMEBIN, 
      LASTBIN};

const static int  NFRAMEWORKBINS = LASTBIN - 1;

#endif /* __ONLMONHISTOBINDEFS_H__ */
