/********************************************************************
* PHBFieldMapDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PHBFieldMapDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePHBFieldMapDict();
extern void G__cpp_setup_inheritancePHBFieldMapDict();
extern void G__cpp_setup_typetablePHBFieldMapDict();
extern void G__cpp_setup_memvarPHBFieldMapDict();
extern void G__cpp_setup_globalPHBFieldMapDict();
extern void G__cpp_setup_memfuncPHBFieldMapDict();
extern void G__cpp_setup_funcPHBFieldMapDict();
extern void G__set_cpp_environmentPHBFieldMapDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "PHBFieldMap.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PHBFieldMapDictLN_TObject;
extern G__linked_taginfo G__PHBFieldMapDictLN_string;
extern G__linked_taginfo G__PHBFieldMapDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PHBFieldMapDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHBFieldMapDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PHBFieldMapDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PHBFieldMapDictLN_PHBFieldMap;

/* STUB derived class for protected member access */
